rocketmqHome = "./.rocketmq-ha-demo/controller-2"
configStorePath = "./.rocketmq-ha-demo/controller-2/controller.properties"
controllerType = "Raft"
nodeId = 2
listenAddr = "127.0.0.1:19888"
storagePath = "./.rocketmq-ha-demo/controller-2/raft"
storageBackend = "RocksDB"
enableElectUncleanMaster = false
enableElectUncleanMasterLocal = false

[[raftPeers]]
id = 1
addr = "127.0.0.1:19879"

[[raftPeers]]
id = 2
addr = "127.0.0.1:19889"

[[raftPeers]]
id = 3
addr = "127.0.0.1:19899"
