version: 2
updates:
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `Cargo.lock` in the root directory
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "cargo"
    directory: "/rocketmq-tools/rocketmq-mcp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "cargo"
    directory: "/rocketmq-sre"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/rocketmq-sre/ui"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
