reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - mxsm # username
      - TeslaRustor # username
      - SpaceXCN # username
  
  per_author:
    engineers:
      - repository-owners # group

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group

  '**/*.yml':
    - repository-owners # username
  '.github/**':
    - repository-owners # username

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 2

  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false