placement:
  requireSeparateHosts: true
services:
  namesrv:
    enabled: true
    replicas: 2
  broker:
    enabled: true
    controllerMode: false
    replicas: 2
    minInSyncReplicas: 2
  controller:
    enabled: false
  proxy:
    enabled: true
    replicas: 2
    tls:
      enabled: true
      secretName: rocketmq-proxy-tls
