placement:
  requireSeparateHosts: true
services:
  namesrv:
    enabled: true
    replicas: 2
  broker:
    enabled: true
    replicas: 2
    controllerMode: false
    minInSyncReplicas: 2
  controller:
    enabled: false
  proxy:
    enabled: false
