placement:
  requireSeparateHosts: true
services:
  namesrv:
    enabled: true
    replicas: 2
  broker:
    enabled: true
    replicas: 3
    controllerMode: true
    minInSyncReplicas: 2
  controller:
    enabled: true
    replicas: 3
  proxy:
    enabled: false
