# RocketMQ home installation directory
rocketmqHome = "${user.home}/rocketmq"

# Storage path for KV configuration file
kvConfigPath = "${user.home}/namesrv/kvConfig.json"

# Storage path for nameserver configuration file
configStorePath = "${user.home}/namesrv/namesrv.properties"

# Product environment name
productEnvName = "center"

# Whether to enable cluster test mode
clusterTest = false

# Whether to enable order message feature
orderMessageEnable = false

# Whether to return order topic configuration to broker
returnOrderTopicConfigToBroker = true

# Number of threads to handle client requests, like GET_ROUTEINTO_BY_TOPIC
clientRequestThreadPoolNums = 8

# Number of threads to handle broker or operation requests, like REGISTER_BROKER
defaultThreadPoolNums = 16

# Capacity of queue to hold client requests
clientRequestThreadPoolQueueCapacity = 50000

# Capacity of queue to hold broker or operation requests
defaultThreadPoolQueueCapacity = 10000

# Interval of periodic scanning for non-active broker (milliseconds)
scanNotActiveBrokerInterval = 5000

# Capacity of queue for unregister broker operations
unRegisterBrokerQueueCapacity = 3000

# Whether to support acting master functionality
# The slave can act as master when master node is down to support:
# 1. Lock/unlock message queue operations
# 2. SearchOffset, query maxOffset/minOffset operations
# 3. Query earliest message store time
supportActingMaster = false

# Whether to enable all topic list functionality
enableAllTopicList = true

# Whether to enable topic list functionality
enableTopicList = true

# Whether to notify when minimum broker ID changes
notifyMinBrokerIdChanged = false

# Whether to enable controller in name server
enableControllerInNamesrv = false

# Whether service needs to wait before starting
needWaitForService = false

# Number of seconds to wait for service
waitSecondsForService = 45

# If enabled, topics not in broker registration payload will be deleted from name server
# WARNING:
# 1. Enable this and "enableSingleTopicRegister" in broker config to avoid losing topic route info
# 2. This flag does not support static topics currently
deleteTopicWithBrokerRegistration = false

# Configurations in this black list will not be allowed to update by command
# Try to update these configurations by restarting the process
configBlackList = "configBlackList;configStorePath;kvConfigPath"