// Copyright 2026 The RocketMQ Rust Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by scripts/generate_metric_catalog.py; do not edit manually.

const METRIC_LABELS_0: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::PROCESSOR,
];

const METRIC_LABELS_1: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
];

const METRIC_LABELS_2: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
    labels::MESSAGE_TYPE,
    labels::IS_SYSTEM,
];

const METRIC_LABELS_3: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
    labels::CONSUMER_GROUP,
    labels::IS_RETRY,
    labels::IS_SYSTEM,
];

const METRIC_LABELS_4: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
];

const METRIC_LABELS_5: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
    labels::MESSAGE_TYPE,
];

const METRIC_LABELS_6: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::LANGUAGE,
    labels::VERSION,
    labels::PROTOCOL_TYPE,
];

const METRIC_LABELS_7: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::LANGUAGE,
    labels::VERSION,
    labels::PROTOCOL_TYPE,
    labels::CONSUME_MODE,
    labels::IS_SYSTEM,
];

const METRIC_LABELS_8: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::TOPIC,
    labels::REVIVE_MESSAGE_TYPE,
    labels::PUT_STATUS,
];

const METRIC_LABELS_9: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::TOPIC,
    labels::QUEUE_ID,
    labels::REVIVE_MESSAGE_TYPE,
];

const METRIC_LABELS_10: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::QUEUE_ID,
];

const METRIC_LABELS_11: &[&str] = &[
    labels::PROTOCOL_TYPE,
    labels::REQUEST_CODE,
    labels::RESPONSE_CODE,
    labels::IS_LONG_POLLING,
    labels::RESULT,
];

const METRIC_LABELS_12: &[&str] = &[
    labels::STORAGE_TYPE,
    labels::STORAGE_MEDIUM,
];

const METRIC_LABELS_13: &[&str] = &[
    labels::STORAGE_TYPE,
    labels::STORAGE_MEDIUM,
    labels::TOPIC,
];

const METRIC_LABELS_14: &[&str] = &[];

const METRIC_LABELS_15: &[&str] = &[
    labels::CATEGORY,
];

const METRIC_LABELS_16: &[&str] = &[
    labels::CATEGORY,
    labels::ERRNO,
];

const METRIC_LABELS_17: &[&str] = &[
    labels::CATEGORY,
    labels::REASON,
];

const METRIC_LABELS_18: &[&str] = &[
    labels::OPERATION,
    labels::REASON,
    labels::ERRNO,
];

const METRIC_LABELS_19: &[&str] = &[
    labels::ENGINE,
];

const METRIC_LABELS_20: &[&str] = &[
    labels::FROM,
    labels::TO,
    labels::REASON,
];

const METRIC_LABELS_21: &[&str] = &[
    labels::STORAGE_TYPE,
    labels::STORAGE_MEDIUM,
    labels::TIMER_BOUND_SECONDS,
];

const METRIC_LABELS_22: &[&str] = &[
    labels::STORAGE_TYPE,
    labels::STORAGE_MEDIUM,
    labels::TYPE,
];

const METRIC_LABELS_23: &[&str] = &[
    labels::TOPIC,
    labels::QUEUE_ID,
    labels::FILE_TYPE,
];

const METRIC_LABELS_24: &[&str] = &[
    labels::TOPIC,
    labels::GROUP,
];

const METRIC_LABELS_25: &[&str] = &[
    labels::OPERATION,
    labels::SUCCESS,
    labels::PATH,
];

const METRIC_LABELS_26: &[&str] = &[
    labels::OPERATION,
    labels::SUCCESS,
];

const METRIC_LABELS_27: &[&str] = &[
    labels::SUCCESS,
];

const METRIC_LABELS_28: &[&str] = &[
    labels::NODE_TYPE,
    labels::CLUSTER,
    labels::NODE_ID,
    labels::PROXY_MODE,
];

const METRIC_LABELS_29: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
];

const METRIC_LABELS_30: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::REQUEST_TYPE,
    labels::REQUEST_HANDLE_STATUS,
];

const METRIC_LABELS_31: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::DLEDGER_OPERATION,
    labels::DLEDGER_OPERATION_STATUS,
];

const METRIC_LABELS_32: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::ELECTION_RESULT,
];

const METRIC_LABELS_33: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::REQUEST_TYPE,
];

const METRIC_LABELS_34: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::DLEDGER_OPERATION,
];

const METRIC_LABELS_35: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::LABEL_KEY,
];

const METRIC_LABELS_36: &[&str] = &[
    labels::EVENT,
    labels::RESULT,
];

const METRIC_LABELS_37: &[&str] = &[
    labels::EVENT,
];

const METRIC_LABELS_38: &[&str] = &[
    labels::RESULT,
];

const METRIC_LABELS_39: &[&str] = &[
    labels::SOURCE_KIND,
    labels::RESULT,
];

const METRIC_LABELS_40: &[&str] = &[
    labels::SOURCE_KIND,
    labels::ADDRESS_FAMILY,
];

const METRIC_LABELS_41: &[&str] = &[
    labels::SOURCE_KIND,
    labels::FRESHNESS,
];

const METRIC_LABELS_42: &[&str] = &[
    labels::REASON,
];

const METRIC_LABELS_43: &[&str] = &[
    labels::STAGE,
];

const METRIC_LABELS_44: &[&str] = &[
    labels::REQUEST_TYPE,
    labels::RESULT,
];

const METRIC_LABELS_45: &[&str] = &[
    labels::REQUEST_TYPE,
];

const METRIC_LABELS_46: &[&str] = &[
    labels::STATE,
];

const METRIC_LABELS_47: &[&str] = &[
    labels::OPERATION,
    labels::RESULT,
];

const METRIC_LABELS_48: &[&str] = &[
    labels::SERVICE,
    labels::RELEASE_COMMIT,
    labels::RELEASE_NONCE,
];

const METRIC_LABELS_49: &[&str] = &[
    labels::OPERATION_KIND,
    labels::OPERATION,
    labels::RESULT,
];

const METRIC_LABELS_50: &[&str] = &[
    labels::OPERATION_KIND,
    labels::OPERATION,
];

const METRIC_LABELS_51: &[&str] = &[
    labels::COMPONENT,
    labels::TASK_TYPE,
];

const METRIC_LABELS_52: &[&str] = &[
    labels::COMPONENT,
];

const METRIC_LABELS_53: &[&str] = &[
    labels::COMPONENT,
    labels::BLOCKING_LANE,
];

const METRIC_LABELS_54: &[&str] = &[
    labels::COMPONENT,
    labels::STATE,
    labels::RESULT,
    labels::REASON,
];

const METRIC_LABELS_55: &[&str] = &[
    labels::COMPONENT,
    labels::BUDGET,
    labels::LANE,
];

const METRIC_LABELS_56: &[&str] = &[
    labels::BACKEND,
    labels::OPERATION,
    labels::RESULT,
];

const METRIC_LABELS_57: &[&str] = &[
    labels::BACKEND,
    labels::OPERATION,
    labels::ERROR_KIND,
];

const METRIC_LABELS_58: &[&str] = &[
    labels::BACKEND,
];

const METRIC_LABELS_59: &[&str] = &[
    labels::BACKEND,
    labels::STATE,
];

pub const JAVA_METRICS: &[MetricDescriptor] = &[
    MetricDescriptor {
        name: metrics::PROCESSOR_WATERMARK,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: METRIC_LABELS_0,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::BROKER_PERMISSION,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::BROKER_UP,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::TOPIC_NUMBER,
        kind: MetricKind::ObservableGauge,
        unit: "{topic}",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_GROUP_NUMBER,
        kind: MetricKind::ObservableGauge,
        unit: "{consumer_group}",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGES_IN_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_2,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGES_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::THROUGHPUT_IN_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::THROUGHPUT_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGE_SIZE,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: METRIC_LABELS_5,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::TOPIC_CREATE_EXECUTION_TIME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_GROUP_CREATE_EXECUTION_TIME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_1,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::PRODUCER_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: METRIC_LABELS_6,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: METRIC_LABELS_7,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_LAG_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_LAG_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_INFLIGHT_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_QUEUEING_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_READY_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::SEND_TO_DLQ_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_3,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::COMMIT_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::ROLLBACK_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::FINISH_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::HALF_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::POP_BUFFER_SCAN_TIME_CONSUME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_1,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_IN_MESSAGE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_8,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_OUT_MESSAGE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_9,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_RETRY_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_8,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_10,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_10,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_OFFSET_BUFFER_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "{offset}",
        labels: METRIC_LABELS_1,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_CHECKPOINT_BUFFER_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "{checkpoint}",
        labels: METRIC_LABELS_1,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::RPC_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_11,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::STORAGE_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_12,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_FLUSH_BEHIND_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_12,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_DISPATCH_BEHIND_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_12,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_MESSAGE_RESERVE_TIME,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_12,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::DELAY_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "seconds",
        labels: METRIC_LABELS_13,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_COMMITLOG_SEGMENT_LEASE_ACTIVE,
        kind: MetricKind::ObservableGauge,
        unit: "{lease}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_HA_ACK_LATENCY_MILLIS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_HA_REPLICATION_LAG_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_SENDFILE_BYTES_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_ATTEMPT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_15,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_SUCCESS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_15,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_16,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_SKIPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_17,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_LOCKED_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_15,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MUNLOCK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_16,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_PAGE_CACHE_WARMUP_MILLIS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_STORAGE_DEGRADATION_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_18,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_BATCH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{batch}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_BYTES_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_ENGINE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{transfer}",
        labels: METRIC_LABELS_19,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_FALLBACK_TOTAL,
        kind: MetricKind::Counter,
        unit: "{fallback}",
        labels: METRIC_LABELS_20,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_PARTIAL_WRITE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{write}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMING_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_13,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_13,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_MESSAGE_SNAPSHOT,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_21,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_BYTES_WRITTEN,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_BYTES_READ,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_WRITTEN_SELF,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_WRITTEN_OTHER,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_RATE_CACHE_HIT,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_COMPRESSED,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_READ_AMPLIFICATION_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_READ,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: METRIC_LABELS_22,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_MESSAGES_DISPATCH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_23,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_MESSAGES_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_24,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_GET_MESSAGE_FALLBACK_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_24,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_UPLOAD_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_25,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_DOWNLOAD_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_25,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_RPC_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_25,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_API_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_26,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_DISPATCH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_23,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_DISPATCH_BEHIND,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: METRIC_LABELS_23,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_COUNT,
        kind: MetricKind::ObservableGauge,
        unit: "{entry}",
        labels: METRIC_LABELS_14,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_ACCESS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{access}",
        labels: METRIC_LABELS_27,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_HIT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{hit}",
        labels: METRIC_LABELS_27,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::PROXY_UP,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: METRIC_LABELS_28,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ROLE,
        kind: MetricKind::UpDownCounter,
        unit: "1",
        labels: METRIC_LABELS_29,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_DISK_USAGE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_29,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ACTIVE_BROKER_NUM,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: METRIC_LABELS_29,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_REQUEST_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_30,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_OP_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_31,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_TOTAL_JAVA,
        kind: MetricKind::Counter,
        unit: "{election}",
        labels: METRIC_LABELS_32,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_33,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_OP_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_34,
        source: MetricSource::Controller,
    },
];

pub const RUST_METRICS: &[MetricDescriptor] = &[
    MetricDescriptor {
        name: metrics::SEND_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_4,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::METRICS_LABEL_DROPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{label}",
        labels: METRIC_LABELS_35,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::STORE_APPEND_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_FLUSH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_DISPATCH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_DISK_USAGE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_ATTEMPTED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_ACCEPTED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_WRITTEN_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_INBOUND_DECODED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_LIFECYCLE_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_36,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_LIFECYCLE_LISTENER_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_37,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::CLIENT_SEND_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_SEND_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_CONSUME_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_CONSUME_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_REBALANCE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_ITEMS,
        kind: MetricKind::Gauge,
        unit: "{message}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_BYTES,
        kind: MetricKind::Gauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_OLDEST_AGE,
        kind: MetricKind::Gauge,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_WAITERS,
        kind: MetricKind::Gauge,
        unit: "{waiter}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_REFRESH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{refresh}",
        labels: METRIC_LABELS_39,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_ENDPOINT_COUNT,
        kind: MetricKind::Gauge,
        unit: "{endpoint}",
        labels: METRIC_LABELS_40,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_FRESHNESS,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: METRIC_LABELS_41,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_SNAPSHOT_AGE,
        kind: MetricKind::Gauge,
        unit: "s",
        labels: METRIC_LABELS_41,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_FAILOVER_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failover}",
        labels: METRIC_LABELS_42,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_REQUEST_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_BROKER_REGISTRATIONS,
        kind: MetricKind::Counter,
        unit: "{registration}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ACTIVE_BROKERS,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_FRESHNESS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_FRESHNESS_SAMPLED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{sample}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_STAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_43,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_CACHE_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_CACHE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_44,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_INFLIGHT,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: METRIC_LABELS_45,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_WAITING,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: METRIC_LABELS_45,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_WRITE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_END_TO_END_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_WRITE_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_DIRTY_TOPICS,
        kind: MetricKind::Histogram,
        unit: "{topic}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_QUEUE_DEPTH,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_BATCH_SIZE,
        kind: MetricKind::Histogram,
        unit: "{request}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_SCAN_BROKERS,
        kind: MetricKind::Histogram,
        unit: "{broker}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_SCAN_DURATION,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_44,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REQUEST_HANDLER_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_44,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_RESPONSE_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: METRIC_LABELS_45,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_BODY_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: METRIC_LABELS_43,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_DECODE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_MUTATION_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_43,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_SNAPSHOT_REBUILDS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{snapshot}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_OLDEST_AGE,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_GENERATION,
        kind: MetricKind::ObservableGauge,
        unit: "{generation}",
        labels: METRIC_LABELS_46,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_QUEUE_DEPTH,
        kind: MetricKind::ObservableGauge,
        unit: "{command}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_QUEUE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_PERSIST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_BATCH_SIZE,
        kind: MetricKind::Histogram,
        unit: "{command}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_38,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_SECURITY_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_47,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_CONNECTION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: METRIC_LABELS_37,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ACTIVE_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: METRIC_LABELS_14,
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_TOTAL,
        kind: MetricKind::Counter,
        unit: "{election}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_LEADER_CHANGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{change}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ACTIVE_BROKERS,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_QUORUM_HEALTH,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_HEARTBEAT_AGE,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_STALE_BROKERS,
        kind: MetricKind::Gauge,
        unit: "{broker}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_FORWARD_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_14,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_ACTIVE_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: METRIC_LABELS_38,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_RELOAD_TOTAL,
        kind: MetricKind::Counter,
        unit: "{reload}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_ACTIVE,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_EXPIRY_TIMESTAMP_SECONDS,
        kind: MetricKind::Gauge,
        unit: "s",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_AUDIT_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_AUTO_RESTORE_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_ROLLBACK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::RELEASE_INFO,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: METRIC_LABELS_48,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::MCP_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: METRIC_LABELS_49,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_50,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: METRIC_LABELS_49,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_CACHE_OPERATIONS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: METRIC_LABELS_38,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_RATE_LIMIT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{decision}",
        labels: METRIC_LABELS_38,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_BACKLOG,
        kind: MetricKind::Gauge,
        unit: "{record}",
        labels: METRIC_LABELS_14,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_DROPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{record}",
        labels: METRIC_LABELS_42,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_FAILURES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: METRIC_LABELS_42,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_TASKS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: METRIC_LABELS_51,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_TASK_GROUPS,
        kind: MetricKind::Gauge,
        unit: "{group}",
        labels: METRIC_LABELS_52,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_LONG_RUNNING_TASKS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: METRIC_LABELS_51,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_QUEUED,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: METRIC_LABELS_53,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_RUNNING,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: METRIC_LABELS_53,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_TIMEOUTS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: METRIC_LABELS_53,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_LIFECYCLE_TRANSITIONS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{transition}",
        labels: METRIC_LABELS_54,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_ITEMS,
        kind: MetricKind::ObservableGauge,
        unit: "{item}",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_OLDEST_AGE_MILLIS,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_CAPACITY_ITEMS,
        kind: MetricKind::ObservableGauge,
        unit: "{item}",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_CAPACITY_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_ACTIVE,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_REJECTED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{rejection}",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_CACHE_USAGE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_CACHE_BUDGET_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: METRIC_LABELS_55,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RECEIPT_RENEWAL_DUE_LAG_MICROS,
        kind: MetricKind::ObservableGauge,
        unit: "us",
        labels: METRIC_LABELS_52,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RECEIPT_RENEWAL_EXPIRED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{receipt}",
        labels: METRIC_LABELS_52,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::DASHBOARD_STORAGE_OPERATIONS_TOTAL,
        kind: MetricKind::Counter,
        unit: "",
        labels: METRIC_LABELS_56,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::DASHBOARD_STORAGE_OPERATION_DURATION_MILLISECONDS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: METRIC_LABELS_56,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::DASHBOARD_STORAGE_OPERATION_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "",
        labels: METRIC_LABELS_57,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::DASHBOARD_STORAGE_CAPACITY_BYTES,
        kind: MetricKind::Gauge,
        unit: "By",
        labels: METRIC_LABELS_58,
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::DASHBOARD_STORAGE_POOL_CONNECTIONS,
        kind: MetricKind::Gauge,
        unit: "",
        labels: METRIC_LABELS_59,
        source: MetricSource::Observability,
    },
];
