apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rocketmq
resources:
  - manifest.yaml
images:
  - name: rocketmq-rust/broker
    newName: rocketmq-rust/broker
    newTag: local
  - name: rocketmq-rust/namesrv
    newName: rocketmq-rust/namesrv
    newTag: local
  - name: rocketmq-rust/controller
    newName: rocketmq-rust/controller
    newTag: local
  - name: rocketmq-rust/proxy
    newName: rocketmq-rust/proxy
    newTag: local
  - name: rocketmq-rust/mcp
    newName: rocketmq-rust/mcp
    newTag: local
