#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Enhancement Request
title: "[Enhancement✨] "
description: Suggest an improvement to existing functionality
labels: [ "enhancement✨" ]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: What is the current behavior that needs improvement?
      placeholder: Currently, the producer API requires...

  - type: textarea
    attributes:
      label: Proposed Enhancement
      description: How would you improve it?
      placeholder: |
        Make the API more ergonomic by...
        
        Example:
        ```rust
        // Current
        let producer = Producer::new().with_config(config);
        
        // Proposed
        let producer = Producer::builder().config(config).build();
        ```

  - type: textarea
    attributes:
      label: Benefits
      description: What are the benefits of this enhancement?
      placeholder: |
        - Better developer experience
        - More consistent with Rust idioms
        - Reduces boilerplate code

  - type: textarea
    attributes:
      label: Additional Context
      description: Links, references, or examples
