# Copyright 2023 The RocketMQ Rust Authors
# Licensed under the Apache License, Version 2.0.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: 10.96.0.0/16
nodes:
  - role: control-plane
    labels:
      topology.kubernetes.io/zone: phase00-local
