apiVersion: v1
kind: Service
metadata:
  name: rocketmq-sre-connector
  namespace: rocketmq-system
spec:
  selector:
    app.kubernetes.io/instance: rocketmq
    rocketmqrust.com/service: mcp
  ports:
    - name: connector-http
      port: 8091
      targetPort: connector-http
