FROM node:24-alpine AS builder

WORKDIR /workspace/rocketmq-sre/ui
ARG VITE_SRE_AUTH_MODE
ARG VITE_SRE_DEV_SUBJECT
ARG VITE_SRE_DEV_DISPLAY_NAME
ARG VITE_SRE_DEV_TENANT
ARG VITE_SRE_DEV_CLUSTERS
ARG VITE_SRE_DEV_ROLES
ARG VITE_SRE_DEV_TOKEN
ARG VITE_SRE_OIDC_AUTHORITY
ARG VITE_SRE_OIDC_CLIENT_ID
ARG VITE_SRE_OIDC_REDIRECT_URI
ARG VITE_SRE_OIDC_POST_LOGOUT_REDIRECT_URI
ARG VITE_SRE_OIDC_SCOPE
ENV VITE_SRE_AUTH_MODE=$VITE_SRE_AUTH_MODE \
    VITE_SRE_DEV_SUBJECT=$VITE_SRE_DEV_SUBJECT \
    VITE_SRE_DEV_DISPLAY_NAME=$VITE_SRE_DEV_DISPLAY_NAME \
    VITE_SRE_DEV_TENANT=$VITE_SRE_DEV_TENANT \
    VITE_SRE_DEV_CLUSTERS=$VITE_SRE_DEV_CLUSTERS \
    VITE_SRE_DEV_ROLES=$VITE_SRE_DEV_ROLES \
    VITE_SRE_DEV_TOKEN=$VITE_SRE_DEV_TOKEN \
    VITE_SRE_OIDC_AUTHORITY=$VITE_SRE_OIDC_AUTHORITY \
    VITE_SRE_OIDC_CLIENT_ID=$VITE_SRE_OIDC_CLIENT_ID \
    VITE_SRE_OIDC_REDIRECT_URI=$VITE_SRE_OIDC_REDIRECT_URI \
    VITE_SRE_OIDC_POST_LOGOUT_REDIRECT_URI=$VITE_SRE_OIDC_POST_LOGOUT_REDIRECT_URI \
    VITE_SRE_OIDC_SCOPE=$VITE_SRE_OIDC_SCOPE
COPY rocketmq-ai/rocketmq-sre/ui/package.json rocketmq-ai/rocketmq-sre/ui/package-lock.json ./
RUN npm ci
COPY rocketmq-ai/rocketmq-sre/ui/ ./
COPY rocketmq-ai/rocketmq-sre/openapi/ ../openapi/
RUN npm run build

FROM nginx:1.29-alpine
COPY rocketmq-ai/rocketmq-sre/deploy/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /workspace/rocketmq-sre/ui/dist /usr/share/nginx/html
EXPOSE 3004
