import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'overview/capability-matrix',
    'overview/release-scope',
    'release-notes/index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/local-source',
        'getting-started/quick-start',
        'getting-started/basic-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/module-map',
        'architecture/message-lifecycle',
        'architecture/runtime',
        'architecture/message-model',
        'architecture/storage',
        'architecture/nameserver',
        'architecture/broker',
        'architecture/client',
        'architecture/protocol-transport',
        'architecture/storage-backends',
        'architecture/ha-controller',
        'architecture/proxy',
        'architecture/security',
        'architecture/errors-observability',
        'architecture/decisions',
      ],
    },
    {
      type: 'category',
      label: 'Producer',
      collapsible: true,
      collapsed: true,
      items: [
        'producer/overview',
        'producer/sending-messages',
        'producer/transaction-messages',
      ],
    },
    {
      type: 'category',
      label: 'Consumer',
      collapsible: true,
      collapsed: true,
      items: [
        'consumer/overview',
        'consumer/push-consumer',
        'consumer/pull-consumer',
        'consumer/classic-pull-compatibility',
        'consumer/pop',
        'consumer/message-filtering',
      ],
    },
    {
      type: 'category',
      label: 'Application Guides',
      collapsible: true,
      collapsed: true,
      items: [
        'guides/delivery-and-retry',
        'guides/ordered-messages',
        'guides/delay-and-recall',
        'guides/request-reply',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: true,
      collapsed: true,
      items: [
        'deployment/overview',
        'deployment/containers',
        'deployment/multi-node',
        'deployment/high-availability',
        'deployment/proxy',
        'deployment/kubernetes',
        'deployment/security',
        'deployment/production-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsible: true,
      collapsed: true,
      items: [
        'operations/first-diagnosis',
        'operations/admin',
        'operations/monitoring',
        'operations/troubleshooting',
        'operations/capacity-performance',
        'operations/maintenance',
        'operations/backup-recovery',
        'operations/upgrade-rollback',
        'operations/offline-tools',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        'configuration/broker-config',
        'configuration/client-config',
        'configuration/performance-tuning',
        'configuration/observability',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: true,
      items: [
        'reference/index',
        'reference/service-configuration',
        'reference/features-platforms',
        'reference/errors',
        'reference/protocol-compatibility',
        'reference/admin-cli',
        'reference/rust-api',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsible: true,
      collapsed: true,
      items: ['migration/java-to-rust', 'migration/rust-api'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      collapsible: true,
      collapsed: true,
      items: [
        'ecosystem/overview',
        'ecosystem/dashboards',
        'ecosystem/dashboard-web',
        'ecosystem/dashboard-desktop',
        'ecosystem/mcp',
        'ecosystem/mcp-control',
        'ecosystem/ai-sre',
        'ecosystem/ai-sre-deployment',
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/common-issues',
        'faq/performance',
        'faq/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsible: true,
      collapsed: true,
      items: [
        'contributing/overview',
        'contributing/development-guide',
        'contributing/documentation',
        'contributing/coding-standards',
        'contributing/testing',
        'contributing/release-engineering',
      ],
    },
    'author',
  ],
};

export default sidebars;
