// Copyright 2023 The RocketMQ Rust Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::semantic::labels;
use crate::semantic::metrics;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MetricKind {
    Counter,
    Gauge,
    Histogram,
    ObservableGauge,
    UpDownCounter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MetricSource {
    Broker,
    Client,
    NameServer,
    Pop,
    Remoting,
    Store,
    Timer,
    RocksDb,
    TieredStore,
    Proxy,
    Controller,
    Observability,
    Mcp,
    Runtime,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MetricDescriptor {
    pub name: &'static str,
    pub kind: MetricKind,
    pub unit: &'static str,
    pub labels: &'static [&'static str],
    pub source: MetricSource,
}

const BASE_NODE_LABELS: &[&str] = &[labels::CLUSTER, labels::NODE_TYPE, labels::NODE_ID];
const BROKER_TOPIC_LABELS: &[&str] = &[labels::CLUSTER, labels::NODE_TYPE, labels::NODE_ID, labels::TOPIC];
const BROKER_IN_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
    labels::MESSAGE_TYPE,
    labels::IS_SYSTEM,
];
const BROKER_OUT_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::TOPIC,
    labels::CONSUMER_GROUP,
    labels::IS_RETRY,
    labels::IS_SYSTEM,
];
const BROKER_CONNECTION_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::LANGUAGE,
    labels::VERSION,
    labels::PROTOCOL_TYPE,
];
const BROKER_CONSUMER_CONNECTION_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::LANGUAGE,
    labels::VERSION,
    labels::PROTOCOL_TYPE,
    labels::CONSUME_MODE,
    labels::IS_SYSTEM,
];
const POP_REVIVE_IN_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::TOPIC,
    labels::REVIVE_MESSAGE_TYPE,
    labels::PUT_STATUS,
];
const POP_REVIVE_OUT_LABELS: &[&str] = &[
    labels::CLUSTER,
    labels::NODE_TYPE,
    labels::NODE_ID,
    labels::CONSUMER_GROUP,
    labels::TOPIC,
    labels::QUEUE_ID,
    labels::REVIVE_MESSAGE_TYPE,
];
const POP_QUEUE_LABELS: &[&str] = &[labels::CLUSTER, labels::NODE_TYPE, labels::NODE_ID, labels::QUEUE_ID];
const REMOTING_RPC_LABELS: &[&str] = &[
    labels::PROTOCOL_TYPE,
    labels::REQUEST_CODE,
    labels::RESPONSE_CODE,
    labels::IS_LONG_POLLING,
    labels::RESULT,
];
const REMOTING_LIFECYCLE_LABELS: &[&str] = &[labels::EVENT, labels::RESULT];
const REMOTING_LIFECYCLE_LISTENER_LABELS: &[&str] = &[labels::EVENT];
const STORE_STORAGE_LABELS: &[&str] = &[labels::STORAGE_TYPE, labels::STORAGE_MEDIUM];
const STORE_TOPIC_LABELS: &[&str] = &[labels::STORAGE_TYPE, labels::STORAGE_MEDIUM, labels::TOPIC];
const STORE_MEMORY_LOCK_CATEGORY_LABELS: &[&str] = &[labels::CATEGORY];
const STORE_MEMORY_LOCK_ERRNO_LABELS: &[&str] = &[labels::CATEGORY, labels::ERRNO];
const STORE_MEMORY_LOCK_SKIP_LABELS: &[&str] = &[labels::CATEGORY, labels::REASON];
const STORE_LINUX_STORAGE_DEGRADATION_LABELS: &[&str] = &[labels::OPERATION, labels::REASON, labels::ERRNO];
const STORE_TRANSFER_ENGINE_LABELS: &[&str] = &[labels::ENGINE];
const STORE_TRANSFER_FALLBACK_LABELS: &[&str] = &[labels::FROM, labels::TO, labels::REASON];
const TIMER_BOUND_LABELS: &[&str] = &[
    labels::STORAGE_TYPE,
    labels::STORAGE_MEDIUM,
    labels::TIMER_BOUND_SECONDS,
];
const ROCKSDB_STORAGE_LABELS: &[&str] = &[labels::STORAGE_TYPE, labels::STORAGE_MEDIUM, labels::TYPE];
const TIERED_PROVIDER_LABELS: &[&str] = &[labels::OPERATION, labels::SUCCESS, labels::PATH];
const TIERED_MESSAGE_OUT_LABELS: &[&str] = &[labels::TOPIC, labels::GROUP];
const TIERED_DISPATCH_LABELS: &[&str] = &[labels::TOPIC, labels::QUEUE_ID, labels::FILE_TYPE];
const PROXY_UP_LABELS: &[&str] = &[labels::NODE_TYPE, labels::CLUSTER, labels::NODE_ID, labels::PROXY_MODE];
const CONTROLLER_BASE_LABELS: &[&str] = &[labels::ADDRESS, labels::GROUP, labels::PEER_ID];
const CONTROLLER_REQUEST_LABELS: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::REQUEST_TYPE,
    labels::REQUEST_HANDLE_STATUS,
];
const CONTROLLER_DLEDGER_LABELS: &[&str] = &[
    labels::ADDRESS,
    labels::GROUP,
    labels::PEER_ID,
    labels::DLEDGER_OPERATION,
    labels::DLEDGER_OPERATION_STATUS,
];
const CONTROLLER_ELECTION_LABELS: &[&str] = &[labels::ADDRESS, labels::GROUP, labels::PEER_ID, labels::ELECTION_RESULT];
const BROKER_LABEL_DROPPED_LABELS: &[&str] = &[labels::CLUSTER, labels::NODE_TYPE, labels::NODE_ID, labels::LABEL_KEY];
const MCP_OPERATION_LABELS: &[&str] = &[labels::OPERATION_KIND, labels::OPERATION];
const MCP_OPERATION_RESULT_LABELS: &[&str] = &[labels::OPERATION_KIND, labels::OPERATION, labels::RESULT];
const RUNTIME_TASK_LABELS: &[&str] = &[labels::COMPONENT, labels::TASK_TYPE];
const RUNTIME_BLOCKING_LABELS: &[&str] = &[labels::COMPONENT, labels::BLOCKING_LANE];
const RUNTIME_LIFECYCLE_LABELS: &[&str] = &[labels::COMPONENT, labels::STATE, labels::RESULT, labels::REASON];
const RESOURCE_QUEUE_LABELS: &[&str] = &[labels::COMPONENT, labels::BUDGET, labels::LANE];
const RESOURCE_CACHE_LABELS: &[&str] = &[labels::COMPONENT, labels::BUDGET, labels::LANE];
const CLIENT_NAMESRV_REFRESH_LABELS: &[&str] = &[labels::SOURCE_KIND, labels::RESULT];
const CLIENT_NAMESRV_ENDPOINT_LABELS: &[&str] = &[labels::SOURCE_KIND, labels::ADDRESS_FAMILY];
const CLIENT_NAMESRV_STATE_LABELS: &[&str] = &[labels::SOURCE_KIND, labels::FRESHNESS];
const CLIENT_NAMESRV_FAILOVER_LABELS: &[&str] = &[labels::REASON];

pub const JAVA_METRICS: &[MetricDescriptor] = &[
    MetricDescriptor {
        name: metrics::PROCESSOR_WATERMARK,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: &[labels::CLUSTER, labels::NODE_TYPE, labels::NODE_ID, labels::PROCESSOR],
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::BROKER_PERMISSION,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::BROKER_UP,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::TOPIC_NUMBER,
        kind: MetricKind::ObservableGauge,
        unit: "{topic}",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_GROUP_NUMBER,
        kind: MetricKind::ObservableGauge,
        unit: "{consumer_group}",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGES_IN_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: BROKER_IN_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGES_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::THROUGHPUT_IN_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::THROUGHPUT_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::MESSAGE_SIZE,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: &[
            labels::CLUSTER,
            labels::NODE_TYPE,
            labels::NODE_ID,
            labels::TOPIC,
            labels::MESSAGE_TYPE,
        ],
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::TOPIC_CREATE_EXECUTION_TIME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_GROUP_CREATE_EXECUTION_TIME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::PRODUCER_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: BROKER_CONNECTION_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: BROKER_CONSUMER_CONNECTION_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_LAG_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_LAG_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_INFLIGHT_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_QUEUEING_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::CONSUMER_READY_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::SEND_TO_DLQ_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: BROKER_OUT_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::COMMIT_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::ROLLBACK_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::FINISH_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::HALF_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::POP_BUFFER_SCAN_TIME_CONSUME,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_IN_MESSAGE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: POP_REVIVE_IN_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_OUT_MESSAGE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: POP_REVIVE_OUT_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_RETRY_MESSAGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: POP_REVIVE_IN_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: POP_QUEUE_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_REVIVE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: POP_QUEUE_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_OFFSET_BUFFER_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "{offset}",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::POP_CHECKPOINT_BUFFER_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "{checkpoint}",
        labels: BASE_NODE_LABELS,
        source: MetricSource::Pop,
    },
    MetricDescriptor {
        name: metrics::RPC_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: REMOTING_RPC_LABELS,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::STORAGE_SIZE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: STORE_STORAGE_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_FLUSH_BEHIND_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: STORE_STORAGE_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_DISPATCH_BEHIND_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: STORE_STORAGE_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORAGE_MESSAGE_RESERVE_TIME,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: STORE_STORAGE_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::DELAY_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "seconds",
        labels: STORE_TOPIC_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_COMMITLOG_SEGMENT_LEASE_ACTIVE,
        kind: MetricKind::ObservableGauge,
        unit: "{lease}",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_HA_ACK_LATENCY_MILLIS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_HA_REPLICATION_LAG_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_SENDFILE_BYTES_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_ATTEMPT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_MEMORY_LOCK_CATEGORY_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_SUCCESS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_MEMORY_LOCK_CATEGORY_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_MEMORY_LOCK_ERRNO_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MLOCK_SKIPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_MEMORY_LOCK_SKIP_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_LOCKED_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: STORE_MEMORY_LOCK_CATEGORY_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_MUNLOCK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_MEMORY_LOCK_ERRNO_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_PAGE_CACHE_WARMUP_MILLIS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_LINUX_STORAGE_DEGRADATION_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: STORE_LINUX_STORAGE_DEGRADATION_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_BATCH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{batch}",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_BYTES_TOTAL,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_ENGINE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{transfer}",
        labels: STORE_TRANSFER_ENGINE_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_FALLBACK_TOTAL,
        kind: MetricKind::Counter,
        unit: "{fallback}",
        labels: STORE_TRANSFER_FALLBACK_LABELS,
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_TRANSFER_PARTIAL_WRITE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{write}",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_LAG,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_LATENCY,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMING_MESSAGES,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_ENQUEUE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: STORE_TOPIC_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_DEQUEUE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: STORE_TOPIC_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::TIMER_MESSAGE_SNAPSHOT,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: TIMER_BOUND_LABELS,
        source: MetricSource::Timer,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_BYTES_WRITTEN,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_BYTES_READ,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_WRITTEN_SELF,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_WRITTEN_OTHER,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_RATE_CACHE_HIT,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_COMPRESSED,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_READ_AMPLIFICATION_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::ROCKSDB_TIMES_READ,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: ROCKSDB_STORAGE_LABELS,
        source: MetricSource::RocksDb,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_MESSAGES_DISPATCH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: TIERED_DISPATCH_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_MESSAGES_OUT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: TIERED_MESSAGE_OUT_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_GET_MESSAGE_FALLBACK_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: TIERED_MESSAGE_OUT_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_UPLOAD_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: TIERED_PROVIDER_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_DOWNLOAD_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: TIERED_PROVIDER_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_PROVIDER_RPC_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: TIERED_PROVIDER_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_API_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[labels::OPERATION, labels::SUCCESS],
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_DISPATCH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: TIERED_DISPATCH_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_DISPATCH_BEHIND,
        kind: MetricKind::ObservableGauge,
        unit: "{message}",
        labels: TIERED_DISPATCH_LABELS,
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_COUNT,
        kind: MetricKind::ObservableGauge,
        unit: "{entry}",
        labels: &[],
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_ACCESS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{access}",
        labels: &[labels::SUCCESS],
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::TIERED_STORE_READ_AHEAD_CACHE_HIT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{hit}",
        labels: &[labels::SUCCESS],
        source: MetricSource::TieredStore,
    },
    MetricDescriptor {
        name: metrics::PROXY_UP,
        kind: MetricKind::ObservableGauge,
        unit: "1",
        labels: PROXY_UP_LABELS,
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ROLE,
        kind: MetricKind::UpDownCounter,
        unit: "1",
        labels: CONTROLLER_BASE_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_DISK_USAGE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: CONTROLLER_BASE_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ACTIVE_BROKER_NUM,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: CONTROLLER_BASE_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_REQUEST_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: CONTROLLER_REQUEST_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_OP_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: CONTROLLER_DLEDGER_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_TOTAL_JAVA,
        kind: MetricKind::Counter,
        unit: "{election}",
        labels: CONTROLLER_ELECTION_LABELS,
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::ADDRESS, labels::GROUP, labels::PEER_ID, labels::REQUEST_TYPE],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_DLEDGER_OP_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[
            labels::ADDRESS,
            labels::GROUP,
            labels::PEER_ID,
            labels::DLEDGER_OPERATION,
        ],
        source: MetricSource::Controller,
    },
];

/// Rust-native metrics that are not part of the Java compatibility catalog.
pub const RUST_METRICS: &[MetricDescriptor] = &[
    MetricDescriptor {
        name: metrics::SEND_MESSAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: BROKER_TOPIC_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::METRICS_LABEL_DROPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{label}",
        labels: BROKER_LABEL_DROPPED_LABELS,
        source: MetricSource::Broker,
    },
    MetricDescriptor {
        name: metrics::STORE_APPEND_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_FLUSH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_DISPATCH_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::STORE_DISK_USAGE,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::Store,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_ATTEMPTED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_ACCEPTED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_OUTBOUND_WRITTEN_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_INBOUND_DECODED_PLAINTEXT_BYTES,
        kind: MetricKind::Counter,
        unit: "By",
        labels: &[],
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_LIFECYCLE_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: REMOTING_LIFECYCLE_LABELS,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::TRANSPORT_LIFECYCLE_LISTENER_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: REMOTING_LIFECYCLE_LISTENER_LABELS,
        source: MetricSource::Remoting,
    },
    MetricDescriptor {
        name: metrics::CLIENT_SEND_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_SEND_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_CONSUME_TOTAL,
        kind: MetricKind::Counter,
        unit: "{message}",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_CONSUME_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_REBALANCE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_ITEMS,
        kind: MetricKind::Gauge,
        unit: "{message}",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_BYTES,
        kind: MetricKind::Gauge,
        unit: "By",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_OLDEST_AGE,
        kind: MetricKind::Gauge,
        unit: "ms",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_WAITERS,
        kind: MetricKind::Gauge,
        unit: "{waiter}",
        labels: &[],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_ONEWAY_EGRESS_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_REFRESH_TOTAL,
        kind: MetricKind::Counter,
        unit: "{refresh}",
        labels: CLIENT_NAMESRV_REFRESH_LABELS,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_ENDPOINT_COUNT,
        kind: MetricKind::Gauge,
        unit: "{endpoint}",
        labels: CLIENT_NAMESRV_ENDPOINT_LABELS,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_FRESHNESS,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: CLIENT_NAMESRV_STATE_LABELS,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_DISCOVERY_SNAPSHOT_AGE,
        kind: MetricKind::Gauge,
        unit: "s",
        labels: CLIENT_NAMESRV_STATE_LABELS,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::CLIENT_NAMESRV_FAILOVER_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failover}",
        labels: CLIENT_NAMESRV_FAILOVER_LABELS,
        source: MetricSource::Client,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_REQUEST_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_BROKER_REGISTRATIONS,
        kind: MetricKind::Counter,
        unit: "{registration}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ACTIVE_BROKERS,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_FRESHNESS,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_FRESHNESS_SAMPLED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{sample}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_STAGE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::STAGE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_CACHE_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_CACHE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::REQUEST_TYPE, labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_INFLIGHT,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: &[labels::REQUEST_TYPE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_WORKLOAD_ADMISSION_WAITING,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: &[labels::REQUEST_TYPE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_WRITE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_END_TO_END_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ROUTE_RESPONSE_WRITE_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_DIRTY_TOPICS,
        kind: MetricKind::Histogram,
        unit: "{topic}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_QUEUE_DEPTH,
        kind: MetricKind::ObservableGauge,
        unit: "{request}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_BATCH_SIZE,
        kind: MetricKind::Histogram,
        unit: "{request}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_SCAN_BROKERS,
        kind: MetricKind::Histogram,
        unit: "{broker}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_SCAN_DURATION,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: &[labels::REQUEST_TYPE, labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REQUEST_HANDLER_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::REQUEST_TYPE, labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_RESPONSE_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: &[labels::REQUEST_TYPE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_BODY_BYTES,
        kind: MetricKind::Histogram,
        unit: "By",
        labels: &[labels::STAGE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_REGISTRATION_DECODE_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_MUTATION_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::STAGE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_SNAPSHOT_REBUILDS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{snapshot}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_EXPIRY_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_UNREGISTRATION_OLDEST_AGE,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_GENERATION,
        kind: MetricKind::ObservableGauge,
        unit: "{generation}",
        labels: &[labels::STATE],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_QUEUE_DEPTH,
        kind: MetricKind::ObservableGauge,
        unit: "{command}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_QUEUE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_PERSIST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "us",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_BATCH_SIZE,
        kind: MetricKind::Histogram,
        unit: "{command}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_KV_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_SECURITY_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::OPERATION, labels::RESULT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_CONNECTION_EVENTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{event}",
        labels: &[labels::EVENT],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::NAMESRV_ACTIVE_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: &[],
        source: MetricSource::NameServer,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_TOTAL,
        kind: MetricKind::Counter,
        unit: "{election}",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ELECTION_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_LEADER_CHANGES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{change}",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_ACTIVE_BROKERS,
        kind: MetricKind::ObservableGauge,
        unit: "{broker}",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_QUORUM_HEALTH,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_HEARTBEAT_AGE,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::CONTROLLER_STALE_BROKERS,
        kind: MetricKind::Gauge,
        unit: "{broker}",
        labels: &[],
        source: MetricSource::Controller,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: &[],
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_FORWARD_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: &[],
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_ACTIVE_CONNECTIONS,
        kind: MetricKind::ObservableGauge,
        unit: "{connection}",
        labels: &[],
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::PROXY_GRPC_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: &[labels::RESULT],
        source: MetricSource::Proxy,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_RELOAD_TOTAL,
        kind: MetricKind::Counter,
        unit: "{reload}",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_ACTIVE,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_EXPIRY_TIMESTAMP_SECONDS,
        kind: MetricKind::Gauge,
        unit: "s",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_AUDIT_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_AUTO_RESTORE_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::LOG_FILTER_ROLLBACK_FAILURE_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: &[],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::RELEASE_INFO,
        kind: MetricKind::Gauge,
        unit: "1",
        labels: &[labels::SERVICE, labels::RELEASE_COMMIT, labels::RELEASE_NONCE],
        source: MetricSource::Observability,
    },
    MetricDescriptor {
        name: metrics::MCP_REQUESTS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{request}",
        labels: MCP_OPERATION_RESULT_LABELS,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_REQUEST_LATENCY,
        kind: MetricKind::Histogram,
        unit: "ms",
        labels: MCP_OPERATION_LABELS,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_ERRORS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{error}",
        labels: MCP_OPERATION_RESULT_LABELS,
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_CACHE_OPERATIONS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{operation}",
        labels: &[labels::RESULT],
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_RATE_LIMIT_TOTAL,
        kind: MetricKind::Counter,
        unit: "{decision}",
        labels: &[labels::RESULT],
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_BACKLOG,
        kind: MetricKind::Gauge,
        unit: "{record}",
        labels: &[],
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_DROPPED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{record}",
        labels: &[labels::REASON],
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::MCP_AUDIT_FAILURES_TOTAL,
        kind: MetricKind::Counter,
        unit: "{failure}",
        labels: &[labels::REASON],
        source: MetricSource::Mcp,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_TASKS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: RUNTIME_TASK_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_TASK_GROUPS,
        kind: MetricKind::Gauge,
        unit: "{group}",
        labels: &[labels::COMPONENT],
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_LONG_RUNNING_TASKS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: RUNTIME_TASK_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_QUEUED,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: RUNTIME_BLOCKING_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_RUNNING,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: RUNTIME_BLOCKING_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_BLOCKING_TIMEOUTS,
        kind: MetricKind::Gauge,
        unit: "{task}",
        labels: RUNTIME_BLOCKING_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RUNTIME_LIFECYCLE_TRANSITIONS_TOTAL,
        kind: MetricKind::Counter,
        unit: "{transition}",
        labels: RUNTIME_LIFECYCLE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_ITEMS,
        kind: MetricKind::ObservableGauge,
        unit: "{item}",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_OLDEST_AGE_MILLIS,
        kind: MetricKind::ObservableGauge,
        unit: "ms",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_CAPACITY_ITEMS,
        kind: MetricKind::ObservableGauge,
        unit: "{item}",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_CAPACITY_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_ACTIVE,
        kind: MetricKind::ObservableGauge,
        unit: "{operation}",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_QUEUE_REJECTED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{rejection}",
        labels: RESOURCE_QUEUE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_CACHE_USAGE_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: RESOURCE_CACHE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RESOURCE_CACHE_BUDGET_BYTES,
        kind: MetricKind::ObservableGauge,
        unit: "By",
        labels: RESOURCE_CACHE_LABELS,
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RECEIPT_RENEWAL_DUE_LAG_MICROS,
        kind: MetricKind::ObservableGauge,
        unit: "us",
        labels: &[labels::COMPONENT],
        source: MetricSource::Runtime,
    },
    MetricDescriptor {
        name: metrics::RECEIPT_RENEWAL_EXPIRED_TOTAL,
        kind: MetricKind::Counter,
        unit: "{receipt}",
        labels: &[labels::COMPONENT],
        source: MetricSource::Runtime,
    },
];

pub const fn java_metrics() -> &'static [MetricDescriptor] {
    JAVA_METRICS
}

pub const fn rust_metrics() -> &'static [MetricDescriptor] {
    RUST_METRICS
}

#[cfg(test)]
mod tests;
