{{- $root := . -}}
{{- range $service, $config := .Values.services }}
{{- if $config.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rocketmq-{{ $service }}
  namespace: {{ $root.Release.Namespace }}
  labels:
{{ include "rocketmq.labels" (dict "root" $root "service" $service) | indent 4 }}
spec:
  minAvailable: {{ $config.pdb.minAvailable }}
  selector:
    matchLabels:
{{ include "rocketmq.selectorLabels" (dict "root" $root "service" $service) | indent 6 }}
---
{{- end }}
{{- end }}
