// Copyright 2023 The RocketMQ Rust Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
use crate::persistence::{Revision, StorageMode};
use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum StorageBackend {
    File,
    Sqlite,
    #[serde(rename = "mysql")]
    MySql,
    #[serde(rename = "postgres")]
    Postgres,
}

impl StorageBackend {
    pub fn parse(value: &str) -> Result<Self, String> {
        match value.trim().to_ascii_lowercase().as_str() {
            "file" => Ok(Self::File),
            "sqlite" | "sqlite3" => Ok(Self::Sqlite),
            "mysql" => Ok(Self::MySql),
            "postgres" | "postgresql" => Ok(Self::Postgres),
            _ => Err(format!(
                "unsupported storage backend `{value}`; expected file, sqlite, mysql, or postgres"
            )),
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::File => "file",
            Self::Sqlite => "sqlite",
            Self::MySql => "mysql",
            Self::Postgres => "postgres",
        }
    }

    pub const fn is_sql(self) -> bool {
        matches!(self, Self::Sqlite | Self::MySql | Self::Postgres)
    }
}

/// Persistent Environment identifier. Values are generated by the dashboard
/// and are opaque to HTTP clients.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EnvironmentId(pub String);

impl EnvironmentId {
    pub fn new() -> Self {
        Self(Uuid::now_v7().to_string())
    }
}

impl Default for EnvironmentId {
    fn default() -> Self {
        Self::new()
    }
}

/// Persistent Endpoint identifier. Values are generated by the dashboard.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EndpointId(pub String);

impl EndpointId {
    pub fn new() -> Self {
        Self(Uuid::now_v7().to_string())
    }
}

impl Default for EndpointId {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum EndpointType {
    Nameserver,
    Proxy,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub enum EndpointRole {
    Primary,
    Secondary,
}

impl EndpointRole {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Primary => "primary",
            Self::Secondary => "secondary",
        }
    }

    pub fn parse(value: &str) -> Result<Self, String> {
        match value {
            "primary" => Ok(Self::Primary),
            "secondary" => Ok(Self::Secondary),
            _ => Err("endpoint role is invalid".to_string()),
        }
    }
}

impl EndpointType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Nameserver => "nameserver",
            Self::Proxy => "proxy",
        }
    }

    pub fn parse(value: &str) -> Result<Self, String> {
        match value {
            "nameserver" => Ok(Self::Nameserver),
            "proxy" => Ok(Self::Proxy),
            _ => Err("endpoint type is invalid".to_string()),
        }
    }
}

/// A configured RocketMQ connection target. TLS and VIP settings belong to
/// the Environment because they apply to the complete connection profile.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Endpoint {
    pub endpoint_id: EndpointId,
    pub endpoint_type: EndpointType,
    pub address: String,
    pub role: EndpointRole,
    pub is_enabled: bool,
    pub is_active: bool,
    pub sort_order: i32,
    pub created_at_ms: i64,
    pub updated_at_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DashboardEnvironment {
    pub environment_id: EnvironmentId,
    pub name: String,
    #[serde(rename = "useVIPChannel")]
    pub use_vip_channel: bool,
    #[serde(rename = "useTLS")]
    pub use_tls: bool,
    pub revision: Revision,
    pub created_at_ms: i64,
    pub updated_at_ms: i64,
    pub endpoints: Vec<Endpoint>,
}

impl DashboardEnvironment {
    pub fn validate(&self) -> Result<(), String> {
        if self.environment_id.0.trim().is_empty() || self.name.trim().is_empty() || self.name.len() > 128 {
            return Err("environment identity is invalid".to_string());
        }
        for endpoint in &self.endpoints {
            if endpoint.endpoint_id.0.trim().is_empty()
                || endpoint.address.trim().is_empty()
                || endpoint.address.len() > 512
                || endpoint.sort_order < 0
                || (endpoint.is_active && !endpoint.is_enabled)
            {
                return Err("endpoint is invalid".to_string());
            }
        }
        for endpoint_type in [EndpointType::Nameserver, EndpointType::Proxy] {
            let active = self
                .endpoints
                .iter()
                .filter(|endpoint| endpoint.endpoint_type == endpoint_type && endpoint.is_active)
                .count();
            if active > 1 {
                return Err("only one active endpoint is allowed for each endpoint type".to_string());
            }
        }
        for (index, endpoint) in self.endpoints.iter().enumerate() {
            if self
                .endpoints
                .iter()
                .skip(index + 1)
                .any(|other| other.endpoint_type == endpoint.endpoint_type && other.address == endpoint.address)
            {
                return Err("duplicate endpoint address".to_string());
            }
        }
        Ok(())
    }

    pub fn bootstrap(config: &DashboardConfigView, now_ms: i64) -> Self {
        let mut endpoints = Vec::new();
        for (sort_order, address) in config.namesrv_addr_list.iter().enumerate() {
            endpoints.push(Endpoint {
                endpoint_id: EndpointId::new(),
                endpoint_type: EndpointType::Nameserver,
                address: address.clone(),
                role: if config.current_namesrv.as_deref() == Some(address.as_str()) {
                    EndpointRole::Primary
                } else {
                    EndpointRole::Secondary
                },
                is_enabled: true,
                is_active: config.current_namesrv.as_deref() == Some(address.as_str()),
                sort_order: sort_order as i32,
                created_at_ms: now_ms,
                updated_at_ms: now_ms,
            });
        }
        for (sort_order, address) in config.proxy_addr_list.iter().enumerate() {
            endpoints.push(Endpoint {
                endpoint_id: EndpointId::new(),
                endpoint_type: EndpointType::Proxy,
                address: address.clone(),
                role: if config.current_proxy_addr.as_deref() == Some(address.as_str()) {
                    EndpointRole::Primary
                } else {
                    EndpointRole::Secondary
                },
                is_enabled: true,
                is_active: config.current_proxy_addr.as_deref() == Some(address.as_str()),
                sort_order: sort_order as i32,
                created_at_ms: now_ms,
                updated_at_ms: now_ms,
            });
        }
        Self {
            environment_id: EnvironmentId("00000000-0000-7000-8000-000000000001".to_string()),
            name: "default".to_string(),
            use_vip_channel: config.use_vip_channel,
            use_tls: config.use_tls,
            revision: Revision(1),
            created_at_ms: now_ms,
            updated_at_ms: now_ms,
            endpoints,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct EndpointView {
    pub endpoint_id: EndpointId,
    pub endpoint_type: EndpointType,
    pub address: String,
    pub role: EndpointRole,
    pub is_enabled: bool,
    pub is_active: bool,
    pub sort_order: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DashboardConfigView {
    pub environment_id: EnvironmentId,
    pub environment_name: String,
    pub revision: Revision,
    pub endpoints: Vec<EndpointView>,
    pub current_namesrv: Option<String>,
    pub namesrv_addr_list: Vec<String>,
    #[serde(rename = "useVIPChannel")]
    pub use_vip_channel: bool,
    #[serde(rename = "useTLS")]
    pub use_tls: bool,
    pub current_proxy_addr: Option<String>,
    pub proxy_addr_list: Vec<String>,
    pub storage_backend: StorageBackend,
    pub storage_mode: StorageMode,
}

impl DashboardConfigView {
    pub fn from_environment(environment: &DashboardEnvironment, storage_backend: StorageBackend) -> Self {
        let mut sorted_endpoints = environment.endpoints.clone();
        sorted_endpoints.sort_by(|left, right| {
            endpoint_type_sort_key(left.endpoint_type)
                .cmp(&endpoint_type_sort_key(right.endpoint_type))
                .then_with(|| left.sort_order.cmp(&right.sort_order))
                .then_with(|| left.endpoint_id.0.cmp(&right.endpoint_id.0))
        });
        let endpoints = sorted_endpoints
            .iter()
            .map(|endpoint| EndpointView {
                endpoint_id: endpoint.endpoint_id.clone(),
                endpoint_type: endpoint.endpoint_type,
                address: endpoint.address.clone(),
                role: endpoint.role,
                is_enabled: endpoint.is_enabled,
                is_active: endpoint.is_active,
                sort_order: endpoint.sort_order,
            })
            .collect();
        let addresses_for = |endpoint_type| {
            sorted_endpoints
                .iter()
                .filter(|endpoint| endpoint.endpoint_type == endpoint_type)
                .map(|endpoint| endpoint.address.clone())
                .collect::<Vec<_>>()
        };
        let active_for = |endpoint_type| {
            sorted_endpoints
                .iter()
                .find(|endpoint| endpoint.endpoint_type == endpoint_type && endpoint.is_active)
                .map(|endpoint| endpoint.address.clone())
        };
        Self {
            environment_id: environment.environment_id.clone(),
            environment_name: environment.name.clone(),
            revision: environment.revision,
            endpoints,
            current_namesrv: active_for(EndpointType::Nameserver),
            namesrv_addr_list: addresses_for(EndpointType::Nameserver),
            use_vip_channel: environment.use_vip_channel,
            use_tls: environment.use_tls,
            current_proxy_addr: active_for(EndpointType::Proxy),
            proxy_addr_list: addresses_for(EndpointType::Proxy),
            storage_backend,
            storage_mode: match storage_backend {
                StorageBackend::File | StorageBackend::Sqlite => StorageMode::SingleNode,
                StorageBackend::MySql | StorageBackend::Postgres => StorageMode::MultiNode,
            },
        }
    }
}

const fn endpoint_type_sort_key(endpoint_type: EndpointType) -> u8 {
    match endpoint_type {
        EndpointType::Nameserver => 0,
        EndpointType::Proxy => 1,
    }
}

/// The published runtime projection of the durable environment aggregate.
///
/// The environment and the operational config are replaced under one lock so
/// HTTP handlers and the admin client never observe different revisions.
#[derive(Debug, Clone)]
pub struct PublishedEnvironment {
    pub environment: DashboardEnvironment,
    pub config: DashboardConfigView,
}

impl PublishedEnvironment {
    pub fn from_environment(environment: DashboardEnvironment, storage_backend: StorageBackend) -> Self {
        let config = DashboardConfigView::from_environment(&environment, storage_backend);
        Self { environment, config }
    }
}

impl Default for DashboardConfigView {
    fn default() -> Self {
        Self {
            environment_id: EnvironmentId("bootstrap".to_string()),
            environment_name: "default".to_string(),
            revision: Revision(0),
            endpoints: Vec::new(),
            current_namesrv: Some("127.0.0.1:9876".to_string()),
            namesrv_addr_list: vec!["127.0.0.1:9876".to_string()],
            use_vip_channel: true,
            use_tls: false,
            current_proxy_addr: Some("127.0.0.1:8080".to_string()),
            proxy_addr_list: vec!["127.0.0.1:8080".to_string()],
            storage_backend: StorageBackend::File,
            storage_mode: StorageMode::SingleNode,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ExpectedRevision {
    pub expected_revision: Revision,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AddressRequest {
    pub address: String,
    pub expected_revision: Revision,
}

/// Identifies an existing endpoint for a mutation without treating its
/// address as a stable key.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct EndpointRequest {
    pub endpoint_id: EndpointId,
    pub expected_revision: Revision,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NameserverListRequest {
    pub namesrv_addr_list: Vec<String>,
    pub current_namesrv: Option<String>,
    pub expected_revision: Revision,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BoolSettingRequest {
    pub enabled: bool,
    pub expected_revision: Revision,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum NameserverAvailabilityStatus {
    Available,
    Unavailable,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NameserverEndpointAvailability {
    pub address: String,
    pub status: NameserverAvailabilityStatus,
    pub checked_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NameserverAvailabilityView {
    pub endpoints: Vec<NameserverEndpointAvailability>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ConfigMutationResult {
    pub message: String,
    pub config: DashboardConfigView,
}
