/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCluster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/handshake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordClusterHandshake"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusterCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/offboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["offboardCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/connector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusterConnectorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/inventory/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestClusterInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/dashboard-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssetDashboardLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topology/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopologyDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvestigations"];
        put?: never;
        post: operations["createInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInvestigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post: operations["createIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["diagnoseIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInspections"];
        put?: never;
        post: operations["createInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInspection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInspectionReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dispositionRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInventorySnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvidenceContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/message-journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMessageJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKnowledgeItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewKnowledgeItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordKnowledgeFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModelCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModelStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModelInvocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/phase2-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPhase2ContractManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonObject: {
            [key: string]: unknown;
        };
        ServiceStatus: {
            /** @enum {string} */
            status: "healthy" | "ready" | "not_ready" | "unavailable";
        };
        WorkflowPage: {
            /** @constant */
            schema_version: "rocketmq-sre.workflow-page.v1";
            items: unknown[];
            /** Format: uuid */
            next_cursor: string | null;
            partial: boolean;
            warnings: string[];
            /** Format: date-time */
            observed_at: string;
        };
        OnboardClusterRequest: {
            /** Format: uuid */
            cluster_id?: string;
            tenant_id: string;
            external_cluster_key: string;
            environment: string;
            region: string;
            rocketmq_version: string;
            deployment_mode: string;
            owner: string;
            /** @default rocketmq-sre-control-plane */
            actor_subject: string;
            /** Format: uuid */
            correlation_id?: string;
        };
        HandshakeRequest: {
            connector_subject: string;
            connector_issuer: string;
            /** Format: uuid */
            correlation_id?: string;
            capability: components["schemas"]["HandshakeCapability"];
            /** @default true */
            compatible: boolean;
            incompatibility_code?: string;
        };
        HandshakeCapability: {
            digest: string;
            protocol_version: string;
            schema_version: string;
            mutation_supported: boolean;
            manifest?: components["schemas"]["JsonObject"];
            data_sources?: components["schemas"]["JsonObject"][];
            /** Format: date-time */
            observed_at?: string;
        };
        OffboardRequest: {
            /** @default rocketmq-sre-control-plane */
            actor_subject: string;
            /** Format: uuid */
            correlation_id?: string;
            reason?: string;
        };
        CreateConversationRequest: {
            /** Format: uuid */
            cluster_id: string;
            question: string;
            resource?: string;
            persist_investigation: boolean;
        };
        CreateInvestigationRequest: {
            /** Format: uuid */
            cluster_id: string;
            /** Format: uuid */
            conversation_id?: string;
            title: string;
            resource?: string;
            symptom_family: string;
        };
        CreateIncidentRequest: {
            /** Format: uuid */
            cluster_id: string;
            title: string;
            resource?: string;
            symptom_family: string;
        };
        PromoteInvestigationRequest: {
            title?: string;
            reason: string;
        };
        CreateInspectionRequest: {
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            template: "cluster_health" | "consumer" | "broker" | "telemetry";
            schedule?: string;
        };
        RecommendationDispositionRequest: {
            /** @enum {string} */
            status: "acknowledged" | "assigned" | "dismissed" | "resolved" | "promoted";
            assignee?: string;
            reason: string;
            /** @enum {string} */
            promote_to?: "investigation" | "incident";
        };
        ImportKnowledgeRequest: {
            /** Format: uuid */
            cluster_id?: string;
            title: string;
            component: string;
            rocketmq_version_range: string;
            source_uri: string;
            source_version: string;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_until?: string;
            owner: string;
            /** Format: date-time */
            review_due_at: string;
            /** @enum {string} */
            sensitivity: "public" | "internal" | "confidential" | "restricted";
            /**
             * @default draft
             * @enum {string}
             */
            review_status: "draft" | "in_review" | "validated" | "deprecated" | "expired";
            /** @default false */
            human_validated: boolean;
            /** @default false */
            ai_generated: boolean;
            markdown: string;
        };
        KnowledgeReviewRequest: {
            /** @enum {string} */
            status: "draft" | "in_review" | "validated" | "deprecated" | "expired";
            /** @default false */
            human_confirmed: boolean;
            reason: string;
        };
        KnowledgeFeedbackRequest: {
            /** @enum {string} */
            kind: "useful" | "incorrect" | "outdated";
            comment?: string;
        };
        Recommendation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            inspection_run_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            severity: string;
            title: string;
            rationale: string;
            evidence_ids: string[];
            /** @enum {string} */
            status: "open" | "acknowledged" | "assigned" | "dismissed" | "resolved" | "promoted";
            assignee?: string | null;
            /** Format: uuid */
            investigation_id?: string | null;
            /** Format: uuid */
            incident_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InspectionRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            template: "cluster_health" | "consumer" | "broker" | "telemetry";
            /** @enum {string} */
            status: "scheduled" | "running" | "needs_evidence" | "completed" | "failed" | "cancelled";
            schedule?: string | null;
            finding_count: number;
            partial: boolean;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InspectionView: {
            run: components["schemas"]["InspectionRun"];
            recommendations: components["schemas"]["Recommendation"][];
            pack_diffs: {
                pack_id: string;
                pack_version: string;
                diff: unknown;
            }[];
        };
        InspectionReport: {
            /** @constant */
            schema_version: "rocketmq-sre.inspection-report.v1";
            /** @enum {string} */
            media_type: "text/markdown; charset=utf-8" | "text/html; charset=utf-8";
            file_name: string;
            content: string;
        };
        SchemaVersion: {
            family: string;
            major: number;
            minor: number;
            required_features?: string[];
        };
        EvidenceReference: {
            uri: string;
            digest: string;
            media_type: string;
            size_bytes: number;
        };
        EvidenceContent: {
            /** @constant */
            storage: "inline";
            value: unknown;
        } | {
            /** @constant */
            storage: "reference";
            value: components["schemas"]["EvidenceReference"];
        };
        EvidenceSnapshot: {
            schema: components["schemas"]["SchemaVersion"];
            /** Format: uuid */
            evidence_id: string;
            /** Format: uuid */
            query_id: string;
            /** Format: uuid */
            correlation_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            source: string;
            resource: string;
            time_range: {
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
            };
            /** Format: date-time */
            observed_at: string;
            freshness_seconds: number;
            partial: boolean;
            warnings: string[];
            /** @enum {string} */
            sensitivity: "public" | "internal" | "confidential" | "restricted";
            /** @enum {string} */
            coverage: "available" | "partial" | "missing" | "not_production_verified";
            content: components["schemas"]["EvidenceContent"];
            content_hash: string;
        };
        EvidencePage: {
            items: components["schemas"]["EvidenceSnapshot"][];
            /** Format: uuid */
            next_cursor: string | null;
            partial: boolean;
        };
        MessageJourneyHop: {
            /** @enum {string} */
            stage: "producer" | "proxy" | "broker" | "store" | "consumer";
            component: string;
            /** Format: date-time */
            observed_at: string;
            /** @enum {string} */
            status: "observed" | "partial" | "missing";
            latency_ms?: number | null;
            /** Format: uuid */
            evidence_id: string;
            detail: string;
        };
        MessageJourney: {
            /** @constant */
            schema_version: "rocketmq-sre.message-journey.v1";
            /** Format: uuid */
            cluster_id: string;
            trace_fingerprint: string;
            topic: string | null;
            queue_id: number | null;
            /** @constant */
            message_body_available: false;
            partial: boolean;
            warnings: string[];
            hops: components["schemas"]["MessageJourneyHop"][];
        };
        WorkflowStreamEvent: {
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            aggregate_type: "conversation" | "investigation" | "incident" | "inspection" | "recommendation";
            aggregate_id: string;
            event_type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
        };
        DiagnosisDispatch: {
            schema_version: string;
            /** Format: uuid */
            incident_id: string;
            /** @constant */
            status: "queued";
            /** @constant */
            execution_eligible: false;
            /** Format: uuid */
            correlation_id: string;
        };
        /**
         * AlertEvent
         * @description Sanitized alert event persisted before correlation.
         */
        AlertEvent: {
            affected_resource: components["schemas"]["AlertEvent__ResourceRef"];
            cluster_id: components["schemas"]["AlertEvent__ClusterId"];
            correlation_key: components["schemas"]["AlertEvent__CorrelationKey"];
            evidence_ids?: components["schemas"]["AlertEvent__EvidenceId"][];
            fingerprint: string;
            id: components["schemas"]["AlertEvent__AlertEventId"];
            labels?: {
                [key: string]: string;
            };
            /** Format: date-time */
            occurred_at: string;
            /** Format: uint32 */
            occurrence_count: number;
            /** Format: date-time */
            received_at: string;
            /** Format: uint64 */
            sequence: number;
            severity: components["schemas"]["AlertEvent__AlertSeverity"];
            source: components["schemas"]["AlertEvent__AlertSource"];
            source_event_id: string;
            status: components["schemas"]["AlertEvent__AlertStatus"];
            summary: string;
            symptom_family: components["schemas"]["AlertEvent__SymptomFamily"];
            tenant_id: components["schemas"]["AlertEvent__TenantId"];
        };
        /**
         * Format: uuid
         * @description Stable identifier for an ingested alert event.
         */
        AlertEvent__AlertEventId: string;
        /**
         * @description Stable alert severity independent of an upstream provider's spelling.
         * @enum {string}
         */
        AlertEvent__AlertSeverity: "info" | "warning" | "error" | "critical";
        /**
         * @description Source that supplied an alert-like event.
         * @enum {string}
         */
        AlertEvent__AlertSource: "alertmanager" | "kubernetes_event" | "health_probe" | "operator_query" | "inspection" | "deployment" | "synthetic_probe";
        /**
         * @description Normalized alert lifecycle.
         * @enum {string}
         */
        AlertEvent__AlertStatus: "firing" | "resolved";
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        AlertEvent__ClusterId: string;
        /** @description Deterministic first-pass key for bounded-window incident correlation. */
        AlertEvent__CorrelationKey: {
            cluster_id: components["schemas"]["AlertEvent__ClusterId"];
            resource_key: string;
            resource_kind: components["schemas"]["AlertEvent__ResourceKind"];
            symptom_family: components["schemas"]["AlertEvent__SymptomFamily"];
            tenant_id: components["schemas"]["AlertEvent__TenantId"];
            /** Format: uint32 */
            window_seconds: number;
            /** Format: date-time */
            window_start: string;
        };
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        AlertEvent__EvidenceId: string;
        /**
         * @description Resource classes accepted by the Phase 2 correlation engine.
         * @enum {string}
         */
        AlertEvent__ResourceKind: "cluster" | "name_server" | "controller" | "broker" | "proxy" | "store" | "topic" | "queue" | "consumer_group" | "producer_group" | "pod" | "node" | "persistent_volume_claim" | "certificate" | "runtime" | "telemetry";
        /** @description Tenant-scoped resource identity used for correlation and topology lookup. */
        AlertEvent__ResourceRef: {
            display_name?: string | null;
            key: string;
            kind: components["schemas"]["AlertEvent__ResourceKind"];
        };
        /** @description Extensible symptom classifier. The value is a stable, lower snake-case ID. */
        AlertEvent__SymptomFamily: string;
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        AlertEvent__TenantId: string;
        /**
         * TopologySnapshot
         * @description Immutable, bounded topology projection used by correlation and UI.
         */
        TopologySnapshot: {
            cluster_id: components["schemas"]["TopologySnapshot__ClusterId"];
            content_hash: string;
            edges: components["schemas"]["TopologySnapshot__TopologyEdge"][];
            /** Format: uint64 */
            freshness_seconds: number;
            id: components["schemas"]["TopologySnapshot__TopologySnapshotId"];
            nodes: components["schemas"]["TopologySnapshot__TopologyNode"][];
            /** Format: date-time */
            observed_at: string;
            partial: boolean;
            tenant_id: components["schemas"]["TopologySnapshot__TenantId"];
            warnings?: string[];
        };
        /**
         * @description Asset classes normalized into the topology graph.
         * @enum {string}
         */
        TopologySnapshot__AssetKind: "name_server" | "controller" | "broker" | "proxy" | "store" | "pod" | "node" | "persistent_volume_claim" | "pod_disruption_budget" | "topic" | "queue" | "producer" | "consumer" | "connection";
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        TopologySnapshot__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        TopologySnapshot__TenantId: string;
        /** @description Directed edge between normalized assets. */
        TopologySnapshot__TopologyEdge: {
            cluster_id: components["schemas"]["TopologySnapshot__ClusterId"];
            content_hash: string;
            /** Format: uint64 */
            freshness_seconds: number;
            from_key: string;
            id: components["schemas"]["TopologySnapshot__TopologyEdgeId"];
            /** Format: date-time */
            observed_at: string;
            partial: boolean;
            relation: components["schemas"]["TopologySnapshot__TopologyRelation"];
            source: string;
            tenant_id: components["schemas"]["TopologySnapshot__TenantId"];
            to_key: string;
        };
        /**
         * Format: uuid
         * @description Stable identifier for a versioned topology edge.
         */
        TopologySnapshot__TopologyEdgeId: string;
        /** @description One normalized node in a point-in-time topology snapshot. */
        TopologySnapshot__TopologyNode: {
            display_name: string;
            key: string;
            kind: components["schemas"]["TopologySnapshot__AssetKind"];
            labels?: {
                [key: string]: string;
            };
            partial: boolean;
            source: string;
        };
        /**
         * @description Versioned topology relationship.
         * @enum {string}
         */
        TopologySnapshot__TopologyRelation: "contains" | "routes_to" | "stores_on" | "runs_on" | "connects_to" | "consumes_from" | "produces_to" | "replicates_to";
        /**
         * Format: uuid
         * @description Stable identifier for an immutable topology snapshot.
         */
        TopologySnapshot__TopologySnapshotId: string;
        /**
         * CapacityForecast
         * @description Capacity trend for one resource and metric.
         */
        CapacityForecast: {
            algorithm_version: string;
            cluster_id: components["schemas"]["CapacityForecast__ClusterId"];
            /** Format: double */
            coverage_ratio: number;
            evidence_ids: components["schemas"]["CapacityForecast__EvidenceId"][];
            /** Format: date-time */
            exhaustion_at?: string | null;
            id: components["schemas"]["CapacityForecast__ForecastId"];
            metric: string;
            /** Format: date-time */
            observed_at: string;
            points: components["schemas"]["CapacityForecast__ForecastPoint"][];
            quality: components["schemas"]["CapacityForecast__ForecastQuality"];
            resource: components["schemas"]["CapacityForecast__ResourceRef"];
            /** Format: date-time */
            sample_end: string;
            /** Format: date-time */
            sample_start: string;
            /** Format: double */
            slope_per_hour?: number | null;
            status: components["schemas"]["CapacityForecast__ForecastStatus"];
            tenant_id: components["schemas"]["CapacityForecast__TenantId"];
            /** Format: double */
            threshold?: number | null;
            /** Format: double */
            volatility?: number | null;
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        CapacityForecast__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        CapacityForecast__EvidenceId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a capacity or backlog forecast.
         */
        CapacityForecast__ForecastId: string;
        /** @description One observed or projected point in a forecast series. */
        CapacityForecast__ForecastPoint: {
            /** Format: date-time */
            at: string;
            projected: boolean;
            /** Format: double */
            value: number;
        };
        /**
         * @description Explainable quality assessment for a forecast.
         * @enum {string}
         */
        CapacityForecast__ForecastQuality: "low" | "medium" | "high";
        /**
         * @description Forecast availability and degradation state.
         * @enum {string}
         */
        CapacityForecast__ForecastStatus: "ready" | "insufficient_data" | "stale" | "unstable_trend" | "unsupported";
        /**
         * @description Resource classes accepted by the Phase 2 correlation engine.
         * @enum {string}
         */
        CapacityForecast__ResourceKind: "cluster" | "name_server" | "controller" | "broker" | "proxy" | "store" | "topic" | "queue" | "consumer_group" | "producer_group" | "pod" | "node" | "persistent_volume_claim" | "certificate" | "runtime" | "telemetry";
        /** @description Tenant-scoped resource identity used for correlation and topology lookup. */
        CapacityForecast__ResourceRef: {
            display_name?: string | null;
            key: string;
            kind: components["schemas"]["CapacityForecast__ResourceKind"];
        };
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        CapacityForecast__TenantId: string;
        /**
         * BacklogEta
         * @description Estimated drain time for a lag, retry, DLQ, POP, or timer backlog.
         */
        BacklogEta: {
            algorithm_version: string;
            /** Format: double */
            arrival_rate_per_second?: number | null;
            backlog_kind: string;
            cluster_id: components["schemas"]["BacklogEta__ClusterId"];
            /** Format: double */
            coverage_ratio: number;
            /** Format: double */
            current_value: number;
            /** Format: double */
            drain_rate_per_second?: number | null;
            /** Format: date-time */
            estimated_clear_at?: string | null;
            evidence_ids: components["schemas"]["BacklogEta__EvidenceId"][];
            id: components["schemas"]["BacklogEta__ForecastId"];
            /** Format: date-time */
            observed_at: string;
            resource: components["schemas"]["BacklogEta__ResourceRef"];
            status: components["schemas"]["BacklogEta__ForecastStatus"];
            tenant_id: components["schemas"]["BacklogEta__TenantId"];
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        BacklogEta__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        BacklogEta__EvidenceId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a capacity or backlog forecast.
         */
        BacklogEta__ForecastId: string;
        /**
         * @description Forecast availability and degradation state.
         * @enum {string}
         */
        BacklogEta__ForecastStatus: "ready" | "insufficient_data" | "stale" | "unstable_trend" | "unsupported";
        /**
         * @description Resource classes accepted by the Phase 2 correlation engine.
         * @enum {string}
         */
        BacklogEta__ResourceKind: "cluster" | "name_server" | "controller" | "broker" | "proxy" | "store" | "topic" | "queue" | "consumer_group" | "producer_group" | "pod" | "node" | "persistent_volume_claim" | "certificate" | "runtime" | "telemetry";
        /** @description Tenant-scoped resource identity used for correlation and topology lookup. */
        BacklogEta__ResourceRef: {
            display_name?: string | null;
            key: string;
            kind: components["schemas"]["BacklogEta__ResourceKind"];
        };
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        BacklogEta__TenantId: string;
        /**
         * WhatIfSimulation
         * @description Read-only what-if result. It never carries an executable action.
         */
        WhatIfSimulation: {
            algorithm_version: string;
            assumptions: string[];
            blast_radius: string[];
            bottlenecks: string[];
            cluster_id: components["schemas"]["WhatIfSimulation__ClusterId"];
            /** Format: date-time */
            created_at: string;
            created_by: string;
            evidence_ids: components["schemas"]["WhatIfSimulation__EvidenceId"][];
            id: components["schemas"]["WhatIfSimulation__SimulationId"];
            input: unknown;
            kind: components["schemas"]["WhatIfSimulation__SimulationKind"];
            missing_assumptions: string[];
            projected_utilization: unknown;
            status: components["schemas"]["WhatIfSimulation__SimulationStatus"];
            tenant_id: components["schemas"]["WhatIfSimulation__TenantId"];
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        WhatIfSimulation__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        WhatIfSimulation__EvidenceId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a read-only what-if simulation.
         */
        WhatIfSimulation__SimulationId: string;
        /**
         * @description Supported deterministic Phase 2 what-if families.
         * @enum {string}
         */
        WhatIfSimulation__SimulationKind: "broker_offline" | "proxy_offline" | "traffic_increase" | "broker_scale_out" | "proxy_scale_out" | "topic_queue_expand" | "version_upgrade" | "configuration_diff";
        /**
         * @description Lifecycle of a read-only simulation.
         * @enum {string}
         */
        WhatIfSimulation__SimulationStatus: "completed" | "insufficient_data" | "unsupported";
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        WhatIfSimulation__TenantId: string;
        /**
         * UpgradeReadinessReport
         * @description Immutable upgrade-readiness assessment.
         */
        UpgradeReadinessReport: {
            cluster_id: components["schemas"]["UpgradeReadinessReport__ClusterId"];
            /** Format: date-time */
            expires_at: string;
            findings: components["schemas"]["UpgradeReadinessReport__ReadinessFinding"][];
            id: components["schemas"]["UpgradeReadinessReport__ReadinessReportId"];
            /** Format: date-time */
            observed_at: string;
            pack_versions: string[];
            status: components["schemas"]["UpgradeReadinessReport__ReadinessStatus"];
            target_version: string;
            tenant_id: components["schemas"]["UpgradeReadinessReport__TenantId"];
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        UpgradeReadinessReport__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        UpgradeReadinessReport__EvidenceId: string;
        /** @description Explainable finding shared by upgrade and disaster-recovery reports. */
        UpgradeReadinessReport__ReadinessFinding: {
            code: string;
            component: string;
            evidence_ids: components["schemas"]["UpgradeReadinessReport__EvidenceId"][];
            remediation_hint?: string | null;
            severity: components["schemas"]["UpgradeReadinessReport__ReadinessFindingSeverity"];
            summary: string;
        };
        /**
         * @description Severity of one deterministic readiness finding.
         * @enum {string}
         */
        UpgradeReadinessReport__ReadinessFindingSeverity: "info" | "warning" | "blocker";
        /**
         * Format: uuid
         * @description Stable identifier for an immutable readiness report.
         */
        UpgradeReadinessReport__ReadinessReportId: string;
        /**
         * @description Aggregate readiness result.
         * @enum {string}
         */
        UpgradeReadinessReport__ReadinessStatus: "ready" | "ready_with_warnings" | "blocked" | "insufficient_data";
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        UpgradeReadinessReport__TenantId: string;
        /**
         * DrReadinessReport
         * @description Immutable disaster-recovery readiness assessment.
         */
        DrReadinessReport: {
            cluster_id: components["schemas"]["DrReadinessReport__ClusterId"];
            /** Format: date-time */
            expires_at: string;
            findings: components["schemas"]["DrReadinessReport__ReadinessFinding"][];
            id: components["schemas"]["DrReadinessReport__ReadinessReportId"];
            /** Format: date-time */
            observed_at: string;
            /** Format: uint64 */
            requested_rpo_seconds: number;
            /** Format: uint64 */
            requested_rto_seconds: number;
            status: components["schemas"]["DrReadinessReport__ReadinessStatus"];
            target_region?: string | null;
            tenant_id: components["schemas"]["DrReadinessReport__TenantId"];
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        DrReadinessReport__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        DrReadinessReport__EvidenceId: string;
        /** @description Explainable finding shared by upgrade and disaster-recovery reports. */
        DrReadinessReport__ReadinessFinding: {
            code: string;
            component: string;
            evidence_ids: components["schemas"]["DrReadinessReport__EvidenceId"][];
            remediation_hint?: string | null;
            severity: components["schemas"]["DrReadinessReport__ReadinessFindingSeverity"];
            summary: string;
        };
        /**
         * @description Severity of one deterministic readiness finding.
         * @enum {string}
         */
        DrReadinessReport__ReadinessFindingSeverity: "info" | "warning" | "blocker";
        /**
         * Format: uuid
         * @description Stable identifier for an immutable readiness report.
         */
        DrReadinessReport__ReadinessReportId: string;
        /**
         * @description Aggregate readiness result.
         * @enum {string}
         */
        DrReadinessReport__ReadinessStatus: "ready" | "ready_with_warnings" | "blocked" | "insufficient_data";
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        DrReadinessReport__TenantId: string;
        /**
         * NotificationDelivery
         * @description One bounded, idempotent notification delivery.
         */
        NotificationDelivery: {
            /** Format: uint16 */
            attempt_count: number;
            cluster_id: components["schemas"]["NotificationDelivery__ClusterId"];
            /** Format: date-time */
            created_at: string;
            deep_link: string;
            /** Format: date-time */
            delivered_at?: string | null;
            delivery_key: string;
            id: components["schemas"]["NotificationDelivery__NotificationDeliveryId"];
            incident_id: components["schemas"]["NotificationDelivery__IncidentId"];
            last_error_code?: string | null;
            /** Format: date-time */
            next_attempt_at?: string | null;
            sanitized_summary: string;
            status: components["schemas"]["NotificationDelivery__NotificationDeliveryStatus"];
            target_id: components["schemas"]["NotificationDelivery__NotificationTargetId"];
            tenant_id: components["schemas"]["NotificationDelivery__TenantId"];
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        NotificationDelivery__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an SRE incident.
         */
        NotificationDelivery__IncidentId: string;
        /**
         * Format: uuid
         * @description Stable identifier for one notification delivery.
         */
        NotificationDelivery__NotificationDeliveryId: string;
        /**
         * @description Durable delivery state for the transactional outbox.
         * @enum {string}
         */
        NotificationDelivery__NotificationDeliveryStatus: "pending" | "delivering" | "delivered" | "retry_scheduled" | "failed";
        /**
         * Format: uuid
         * @description Stable identifier for a notification target.
         */
        NotificationDelivery__NotificationTargetId: string;
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        NotificationDelivery__TenantId: string;
        /**
         * PostmortemDraft
         * @description Mutable postmortem head pointing at immutable revisions.
         */
        PostmortemDraft: {
            cluster_id: components["schemas"]["PostmortemDraft__ClusterId"];
            /** Format: date-time */
            confirmed_at?: string | null;
            confirmed_by?: string | null;
            /** Format: date-time */
            created_at: string;
            created_by: string;
            /** Format: uint32 */
            current_revision: number;
            id: components["schemas"]["PostmortemDraft__PostmortemId"];
            incident_id: components["schemas"]["PostmortemDraft__IncidentId"];
            published_knowledge_item_id?: components["schemas"]["PostmortemDraft__KnowledgeItemId"] | null;
            status: components["schemas"]["PostmortemDraft__PostmortemStatus"];
            tenant_id: components["schemas"]["PostmortemDraft__TenantId"];
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        PostmortemDraft__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an SRE incident.
         */
        PostmortemDraft__IncidentId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a knowledge item.
         */
        PostmortemDraft__KnowledgeItemId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a postmortem.
         */
        PostmortemDraft__PostmortemId: string;
        /**
         * @description Postmortem lifecycle. Publication always requires an explicit human actor.
         * @enum {string}
         */
        PostmortemDraft__PostmortemStatus: "draft" | "in_review" | "confirmed" | "published" | "archived";
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        PostmortemDraft__TenantId: string;
        /**
         * PostmortemRevision
         * @description Immutable content revision with explicit Evidence citations.
         */
        PostmortemRevision: {
            contributing_factors: string[];
            /** Format: date-time */
            created_at: string;
            detection: string;
            edited_by: string;
            effective_actions: string[];
            evidence_ids: components["schemas"]["PostmortemRevision__EvidenceId"][];
            human_confirmed: boolean;
            id: components["schemas"]["PostmortemRevision__PostmortemRevisionId"];
            impact: string;
            ineffective_actions: string[];
            model_invocation_id?: components["schemas"]["PostmortemRevision__ModelInvocationId"] | null;
            postmortem_id: components["schemas"]["PostmortemRevision__PostmortemId"];
            recovery: string;
            /** Format: uint32 */
            revision: number;
            root_causes: string[];
            summary: string;
            timeline: unknown;
        };
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        PostmortemRevision__EvidenceId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a model invocation.
         */
        PostmortemRevision__ModelInvocationId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a postmortem.
         */
        PostmortemRevision__PostmortemId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an immutable postmortem revision.
         */
        PostmortemRevision__PostmortemRevisionId: string;
        /**
         * ActionItem
         * @description Independently tracked postmortem follow-up.
         */
        ActionItem: {
            cluster_id: components["schemas"]["ActionItem__ClusterId"];
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            due_at?: string | null;
            evidence_ids: components["schemas"]["ActionItem__EvidenceId"][];
            execution_journal?: unknown;
            id: components["schemas"]["ActionItem__ActionItemId"];
            incident_id: components["schemas"]["ActionItem__IncidentId"];
            owner?: string | null;
            postmortem_id: components["schemas"]["ActionItem__PostmortemId"];
            status: components["schemas"]["ActionItem__ActionItemStatus"];
            tenant_id: components["schemas"]["ActionItem__TenantId"];
            title: string;
            /** Format: date-time */
            updated_at: string;
            verification?: string | null;
        };
        /**
         * Format: uuid
         * @description Stable identifier for a postmortem action item.
         */
        ActionItem__ActionItemId: string;
        /**
         * @description Action-item lifecycle.
         * @enum {string}
         */
        ActionItem__ActionItemStatus: "open" | "assigned" | "in_progress" | "blocked" | "completed" | "reopened" | "cancelled";
        /**
         * Format: uuid
         * @description Internal identifier for an onboarded cluster.
         */
        ActionItem__ClusterId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an evidence snapshot.
         */
        ActionItem__EvidenceId: string;
        /**
         * Format: uuid
         * @description Stable identifier for an SRE incident.
         */
        ActionItem__IncidentId: string;
        /**
         * Format: uuid
         * @description Stable identifier for a postmortem.
         */
        ActionItem__PostmortemId: string;
        /**
         * Format: uuid
         * @description Stable tenant boundary identifier.
         */
        ActionItem__TenantId: string;
        /**
         * Phase2ContractManifest
         * @description Capability marker returned alongside the Phase 2 API schema.
         */
        Phase2ContractManifest: {
            cluster_mutation_supported: boolean;
            effective_access: string;
            operations: components["schemas"]["Phase2ContractManifest__ReadOnlyOperation"][];
            schema_version: string;
        };
        /**
         * @description Read-only operations frozen into the Phase 2 public contract.
         * @enum {string}
         */
        Phase2ContractManifest__ReadOnlyOperation: "read_alerts" | "read_topology" | "read_forecasts" | "run_simulation" | "read_readiness" | "manage_postmortem_metadata" | "manage_action_item_metadata";
    };
    responses: {
        /** @description Successful scoped response */
        JsonObject: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JsonObject"];
            };
        };
        /** @description Bounded workflow page */
        WorkflowPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WorkflowPage"];
            };
        };
    };
    parameters: {
        Id: string;
        ClusterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency readiness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized clusters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"][];
                };
            };
        };
    };
    onboardCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardClusterRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
            201: components["responses"]["JsonObject"];
        };
    };
    getCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    recordClusterHandshake: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandshakeRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getClusterCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    offboardCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OffboardRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getClusterConnectorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getLatestClusterInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listAssets: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getAssetDashboardLink: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                kind: string;
                external_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getTopology: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getTopologyDiff: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listConversations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listInvestigations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvestigationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    promoteInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteInvestigationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listIncidents: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createIncident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    diagnoseIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued read-only diagnosis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisDispatch"];
                };
            };
        };
    };
    listInspections: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createInspection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInspectionRequest"];
            };
        };
        responses: {
            /** @description Created or completed inspection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    getInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inspection detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    runInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed inspection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    getInspectionReport: {
        parameters: {
            query?: {
                format?: "markdown" | "html";
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionReport"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    dispositionRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationDispositionRequest"];
            };
        };
        responses: {
            /** @description Updated recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
        };
    };
    getInventorySnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listEvidence: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical evidence page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSnapshot"];
                };
            };
        };
    };
    getEvidenceContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized bounded JSON content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getMessageJourney: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata-only message journey */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageJourney"];
                };
            };
        };
    };
    listKnowledge: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    importKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportKnowledgeRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    searchKnowledge: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                q: string;
                rocketmq_version: string;
                component?: string;
                limit?: number;
                include_unvalidated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getKnowledgeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    reviewKnowledgeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeReviewRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    recordKnowledgeFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeFeedbackRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getModelCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getModelStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listModelInvocations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                incident_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    subscribeWorkflowEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream containing WorkflowStreamEvent data frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["WorkflowStreamEvent"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This checked-in Phase 01 OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"];
                };
            };
        };
    };
    getPhase2ContractManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase 2 read-only contract manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Phase2ContractManifest"];
                };
            };
        };
    };
}
