/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCluster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/handshake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordClusterHandshake"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusterCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/offboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["offboardCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/connector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusterConnectorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clusters/{id}/inventory/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestClusterInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/dashboard-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssetDashboardLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topology/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopologyDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvestigations"];
        put?: never;
        post: operations["createInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInvestigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post: operations["createIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["diagnoseIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInspections"];
        put?: never;
        post: operations["createInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInspection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInspectionReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dispositionRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInventorySnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvidenceContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/message-journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMessageJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKnowledgeItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewKnowledgeItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordKnowledgeFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModelCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getModelStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModelInvocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonObject: {
            [key: string]: unknown;
        };
        ServiceStatus: {
            /** @enum {string} */
            status: "healthy" | "ready" | "not_ready" | "unavailable";
        };
        WorkflowPage: {
            /** @constant */
            schema_version: "rocketmq-sre.workflow-page.v1";
            items: unknown[];
            /** Format: uuid */
            next_cursor: string | null;
            partial: boolean;
            warnings: string[];
            /** Format: date-time */
            observed_at: string;
        };
        OnboardClusterRequest: {
            /** Format: uuid */
            cluster_id?: string;
            tenant_id: string;
            external_cluster_key: string;
            environment: string;
            region: string;
            rocketmq_version: string;
            deployment_mode: string;
            owner: string;
            /** @default rocketmq-sre-control-plane */
            actor_subject: string;
            /** Format: uuid */
            correlation_id?: string;
        };
        HandshakeRequest: {
            connector_subject: string;
            connector_issuer: string;
            /** Format: uuid */
            correlation_id?: string;
            capability: components["schemas"]["HandshakeCapability"];
            /** @default true */
            compatible: boolean;
            incompatibility_code?: string;
        };
        HandshakeCapability: {
            digest: string;
            protocol_version: string;
            schema_version: string;
            mutation_supported: boolean;
            manifest?: components["schemas"]["JsonObject"];
            data_sources?: components["schemas"]["JsonObject"][];
            /** Format: date-time */
            observed_at?: string;
        };
        OffboardRequest: {
            /** @default rocketmq-sre-control-plane */
            actor_subject: string;
            /** Format: uuid */
            correlation_id?: string;
            reason?: string;
        };
        CreateConversationRequest: {
            /** Format: uuid */
            cluster_id: string;
            question: string;
            resource?: string;
            persist_investigation: boolean;
        };
        CreateInvestigationRequest: {
            /** Format: uuid */
            cluster_id: string;
            /** Format: uuid */
            conversation_id?: string;
            title: string;
            resource?: string;
            symptom_family: string;
        };
        CreateIncidentRequest: {
            /** Format: uuid */
            cluster_id: string;
            title: string;
            resource?: string;
            symptom_family: string;
        };
        PromoteInvestigationRequest: {
            title?: string;
            reason: string;
        };
        CreateInspectionRequest: {
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            template: "cluster_health" | "consumer" | "broker" | "telemetry";
            schedule?: string;
        };
        RecommendationDispositionRequest: {
            /** @enum {string} */
            status: "acknowledged" | "assigned" | "dismissed" | "resolved" | "promoted";
            assignee?: string;
            reason: string;
            /** @enum {string} */
            promote_to?: "investigation" | "incident";
        };
        ImportKnowledgeRequest: {
            /** Format: uuid */
            cluster_id?: string;
            title: string;
            component: string;
            rocketmq_version_range: string;
            source_uri: string;
            source_version: string;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_until?: string;
            owner: string;
            /** Format: date-time */
            review_due_at: string;
            /** @enum {string} */
            sensitivity: "public" | "internal" | "confidential" | "restricted";
            /**
             * @default draft
             * @enum {string}
             */
            review_status: "draft" | "in_review" | "validated" | "deprecated" | "expired";
            /** @default false */
            human_validated: boolean;
            /** @default false */
            ai_generated: boolean;
            markdown: string;
        };
        KnowledgeReviewRequest: {
            /** @enum {string} */
            status: "draft" | "in_review" | "validated" | "deprecated" | "expired";
            /** @default false */
            human_confirmed: boolean;
            reason: string;
        };
        KnowledgeFeedbackRequest: {
            /** @enum {string} */
            kind: "useful" | "incorrect" | "outdated";
            comment?: string;
        };
        Recommendation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            inspection_run_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            severity: string;
            title: string;
            rationale: string;
            evidence_ids: string[];
            /** @enum {string} */
            status: "open" | "acknowledged" | "assigned" | "dismissed" | "resolved" | "promoted";
            assignee?: string | null;
            /** Format: uuid */
            investigation_id?: string | null;
            /** Format: uuid */
            incident_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InspectionRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            template: "cluster_health" | "consumer" | "broker" | "telemetry";
            /** @enum {string} */
            status: "scheduled" | "running" | "needs_evidence" | "completed" | "failed" | "cancelled";
            schedule?: string | null;
            finding_count: number;
            partial: boolean;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InspectionView: {
            run: components["schemas"]["InspectionRun"];
            recommendations: components["schemas"]["Recommendation"][];
            pack_diffs: {
                pack_id: string;
                pack_version: string;
                diff: unknown;
            }[];
        };
        InspectionReport: {
            /** @constant */
            schema_version: "rocketmq-sre.inspection-report.v1";
            /** @enum {string} */
            media_type: "text/markdown; charset=utf-8" | "text/html; charset=utf-8";
            file_name: string;
            content: string;
        };
        SchemaVersion: {
            family: string;
            major: number;
            minor: number;
            required_features?: string[];
        };
        EvidenceReference: {
            uri: string;
            digest: string;
            media_type: string;
            size_bytes: number;
        };
        EvidenceContent: {
            /** @constant */
            storage: "inline";
            value: unknown;
        } | {
            /** @constant */
            storage: "reference";
            value: components["schemas"]["EvidenceReference"];
        };
        EvidenceSnapshot: {
            schema: components["schemas"]["SchemaVersion"];
            /** Format: uuid */
            evidence_id: string;
            /** Format: uuid */
            query_id: string;
            /** Format: uuid */
            correlation_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            source: string;
            resource: string;
            time_range: {
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
            };
            /** Format: date-time */
            observed_at: string;
            freshness_seconds: number;
            partial: boolean;
            warnings: string[];
            /** @enum {string} */
            sensitivity: "public" | "internal" | "confidential" | "restricted";
            /** @enum {string} */
            coverage: "available" | "partial" | "missing" | "not_production_verified";
            content: components["schemas"]["EvidenceContent"];
            content_hash: string;
        };
        EvidencePage: {
            items: components["schemas"]["EvidenceSnapshot"][];
            /** Format: uuid */
            next_cursor: string | null;
            partial: boolean;
        };
        MessageJourneyHop: {
            /** @enum {string} */
            stage: "producer" | "proxy" | "broker" | "store" | "consumer";
            component: string;
            /** Format: date-time */
            observed_at: string;
            /** @enum {string} */
            status: "observed" | "partial" | "missing";
            latency_ms?: number | null;
            /** Format: uuid */
            evidence_id: string;
            detail: string;
        };
        MessageJourney: {
            /** @constant */
            schema_version: "rocketmq-sre.message-journey.v1";
            /** Format: uuid */
            cluster_id: string;
            trace_fingerprint: string;
            topic: string | null;
            queue_id: number | null;
            /** @constant */
            message_body_available: false;
            partial: boolean;
            warnings: string[];
            hops: components["schemas"]["MessageJourneyHop"][];
        };
        WorkflowStreamEvent: {
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            cluster_id: string;
            /** @enum {string} */
            aggregate_type: "conversation" | "investigation" | "incident" | "inspection" | "recommendation";
            aggregate_id: string;
            event_type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
        };
        DiagnosisDispatch: {
            schema_version: string;
            /** Format: uuid */
            incident_id: string;
            /** @constant */
            status: "queued";
            /** @constant */
            execution_eligible: false;
            /** Format: uuid */
            correlation_id: string;
        };
    };
    responses: {
        /** @description Successful scoped response */
        JsonObject: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JsonObject"];
            };
        };
        /** @description Bounded workflow page */
        WorkflowPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WorkflowPage"];
            };
        };
    };
    parameters: {
        Id: string;
        ClusterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency readiness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized clusters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"][];
                };
            };
        };
    };
    onboardCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardClusterRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
            201: components["responses"]["JsonObject"];
        };
    };
    getCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    recordClusterHandshake: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandshakeRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getClusterCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    offboardCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OffboardRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getClusterConnectorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getLatestClusterInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listAssets: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getAssetDashboardLink: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                kind: string;
                external_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getTopology: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getTopologyDiff: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listConversations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listInvestigations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvestigationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    promoteInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteInvestigationRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listIncidents: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createIncident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    diagnoseIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued read-only diagnosis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisDispatch"];
                };
            };
        };
    };
    listInspections: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    createInspection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInspectionRequest"];
            };
        };
        responses: {
            /** @description Created or completed inspection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    getInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inspection detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    runInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed inspection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionView"];
                };
            };
        };
    };
    getInspectionReport: {
        parameters: {
            query?: {
                format?: "markdown" | "html";
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionReport"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WorkflowPage"];
        };
    };
    dispositionRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationDispositionRequest"];
            };
        };
        responses: {
            /** @description Updated recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
        };
    };
    getInventorySnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listEvidence: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical evidence page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSnapshot"];
                };
            };
        };
    };
    getEvidenceContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized bounded JSON content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getMessageJourney: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata-only message journey */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageJourney"];
                };
            };
        };
    };
    listKnowledge: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    importKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportKnowledgeRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    searchKnowledge: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                q: string;
                rocketmq_version: string;
                component?: string;
                limit?: number;
                include_unvalidated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getKnowledgeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    reviewKnowledgeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeReviewRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    recordKnowledgeFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeFeedbackRequest"];
            };
        };
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getModelCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    getModelStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    listModelInvocations: {
        parameters: {
            query: {
                cluster_id: components["parameters"]["ClusterId"];
                incident_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["JsonObject"];
        };
    };
    subscribeWorkflowEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream containing WorkflowStreamEvent data frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["WorkflowStreamEvent"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This checked-in Phase 01 OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"];
                };
            };
        };
    };
}
