name: Approval

on:
  pull_request_review:
    types: [ submitted ]
permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if approval is from Collaborators
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { pull_request, review } = context.payload;

            // Define your list of collaborators
            const collaborators = ['mxsm', 'TeslaRustor','SpaceXCN']; // Replace with actual GitHub usernames
            console.log('review:', review.state);
            console.log('review:',  review.state === 'approved');
            console.log('Collaborators:', collaborators);
            console.log('Collaborators:',  collaborators.includes(review.user.login));
            // Check if the review is approved and from a collaborator
            const isApprovedByCollaborator = review.state === 'approved' && collaborators.includes(review.user.login);
            console.log('isApprovedByCollaborator:',  isApprovedByCollaborator);
            console.log('pull_request:',  pull_request.number);
            


