name: Add Label on Approval

on:
  pull_request_target:
    types: [submitted, edited]
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if approval is from Collaborators
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { pull_request, review } = context.payload;
            
            // Define your list of collaborators
            const collaborators = ['mxsm', 'TeslaRustor', 'SpaceXCN']; // Replace with actual GitHub usernames

            // Check if the review is approved and from a collaborator
            const isApprovedByCollaborator = review && review.state === 'approved' && collaborators.includes(review.user.login);

            // Return the result to the workflow
            if (isApprovedByCollaborator) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pull_request.number,
                labels: ['approved', 'auto merge']
              });
            }
