name: Add Label on Approval

on:
  pull_request_review:
    types: [ submitted ]
  pull_request:
    types: [ opened, synchronize ]
    
jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if approval is from Collaborators
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { pull_request, review } = context.payload;

            // Define your list of collaborators
            const collaborators = ['mxsm', 'TeslaRustor,'SpaceXCN']; // Replace with actual GitHub usernames

            // Check if the review is approved and from a collaborator
            const isApprovedByCollaborator = review.state === 'approved' && collaborators.includes(review.user.login);

            // Return the result to the workflow
            return { approvedByCollaborator: isApprovedByCollaborator, pullRequestNumber: pull_request.number };

      - name: Add label if approved by Collaborators
        if: steps.check_approval.outputs.approvedByCollaborator == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { pullRequestNumber } = steps.check_approval.outputs;

            // Add your label here
            const labelToAdd = 'approved-by-collaborator';

            // Add the label to the pull request
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: pullRequestNumber,
              labels: ['approved','auto merge']
            });
