name: Add Label on Approval

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if approval is from owner
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { owner } = context.repo;
            const { pull_request, review } = context.payload;

            // Check if the review is approved and from the repository owner
            const isApprovedByOwner = review.state === 'approved' && review.user.login === owner;

            // Return the result to the workflow
            return { approvedByOwner: isApprovedByOwner, pullRequestNumber: pull_request.number };

      - name: Add label if approved by owner
        if: steps.check_approval.outputs.approvedByOwner == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { pullRequestNumber } = steps.check_approval.outputs;

            // Add your label here
            const labelToAdd = 'approved-by-owner';

            // Add the label to the pull request
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: pullRequestNumber,
              labels: [labelToAdd]
            });
