name: Update Labels After Approval

on:
  workflow_run:
    workflows:
      - Remove and Add Multiple Labels on Approval
    types:
      - completed

jobs:
  update-labels:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Workflow Context
        run: echo "Payload: $(cat $GITHUB_EVENT_PATH)"

      - name: Remove multiple labels using github-script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const labelsToRemove = ['waiting-review','ready to review']; // Labels to remove
            const { owner, repo } = context.repo;

            const workflowRunId = context.payload.workflow_run.id;
            const { data: workflowRun } = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: workflowRunId,
            });

            if (workflowRun.pull_requests && workflowRun.pull_requests.length > 0) {
              const issue_number = workflowRun.pull_requests[0].number;

              console.log(`Processing PR #${issue_number} in repository '${owner}/${repo}'.`);

              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner,
                repo,
                issue_number,
              });

              const existingLabelsToRemove = labels
                .filter(label => labelsToRemove.includes(label.name))
                .map(label => label.name);

              for (const label of existingLabelsToRemove) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name: label,
                });
                console.log(`Label '${label}' has been removed.`);
              }

              if (existingLabelsToRemove.length === 0) {
                console.log('No matching labels found to remove.');
              }

              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['approved', 'auto merge'],
              });
              console.log(`Labels 'approved' and 'auto merge' added.`);
            } else {
              throw new Error('No associated pull requests found for this workflow run.');
            }
